import bcrypt from 'bcryptjs'
import crypto from 'crypto'
import express from 'express'
import jwt from 'jsonwebtoken'
import ActivityLog from '../models/ActivityLog.js'
import AdminAccount from '../models/AdminAccount.js'
import Campaign from '../models/Campaign.js'
import Cause from '../models/Cause.js'
import ContactMessage from '../models/ContactMessage.js'
import Donation from '../models/Donation.js'
import Donor from '../models/Donor.js'
import FoundationSetting from '../models/FoundationSetting.js'
import GalleryItem from '../models/GalleryItem.js'
import Partner from '../models/Partner.js'
import Report from '../models/Report.js'
import SiteContent from '../models/SiteContent.js'
import Story from '../models/Story.js'
import Volunteer from '../models/Volunteer.js'
import { requireAdmin } from '../middleware/adminAuth.js'

const router = express.Router()
const models={causes:Cause,campaigns:Campaign,donations:Donation,donors:Donor,volunteers:Volunteer,partners:Partner,stories:Story,messages:ContactMessage,gallery:GalleryItem,reports:Report,content:SiteContent,settings:FoundationSetting,activity:ActivityLog}
const creatable=['causes','campaigns','stories','gallery','reports','content','settings']
const allowedStatuses={donors:['active','blocked','deleted'],volunteers:['new','reviewing','approved','assigned','inactive'],partners:['new','contacted','proposal','active','closed'],messages:['new','read','replied','archived'],causes:['draft','published','archived'],campaigns:['draft','active','completed','paused','archived'],stories:['draft','published','archived'],gallery:['draft','published','archived'],reports:['draft','published','archived']}
const log=async(req,action,resource,id='',details='')=>{try{await ActivityLog.create({actor:req.admin?.email||'admin',action,resource,resourceId:String(id||''),details})}catch{}}
const normalizeEmail=value=>String(value||'').trim().toLowerCase()
const hashResetToken=token=>crypto.createHash('sha256').update(token).digest('hex')

function cmsMedia(item,resource){if(!item)return null;if(resource==='campaigns')return {url:item.coverImage,resourceType:'image'};if(resource==='causes')return {url:item.image,resourceType:'image'};if(resource==='stories')return {url:item.coverImage,resourceType:'image'};if(resource==='gallery')return {url:item.mediaUrl||item.image,resourceType:item.mediaType==='video'?'video':'image'};return null}
function cloudinaryAsset(url,resourceType='image'){const cloudName=String(process.env.CLOUDINARY_CLOUD_NAME||'').trim();if(!cloudName||!url)return null;try{const parsed=new URL(String(url));if(parsed.hostname!=='res.cloudinary.com')return null;const parts=parsed.pathname.split('/').filter(Boolean);if(parts[0]!==cloudName)return null;const uploadIndex=parts.indexOf('upload');if(uploadIndex<0)return null;let assetParts=parts.slice(uploadIndex+1);if(assetParts[0]&&/^v\d+$/.test(assetParts[0]))assetParts=assetParts.slice(1);if(!assetParts.length||assetParts[0]!=='rb-charity-foundation')return null;const last=assetParts.at(-1).replace(/\.[^.]+$/,'');assetParts[assetParts.length-1]=last;return {publicId:assetParts.join('/'),resourceType}}catch{return null}}
async function destroyCloudinaryAsset(media){if(!media?.url)return;const apiKey=String(process.env.CLOUDINARY_API_KEY||'').trim(),apiSecret=String(process.env.CLOUDINARY_API_SECRET||'').trim(),cloudName=String(process.env.CLOUDINARY_CLOUD_NAME||'').trim();if(!apiKey||!apiSecret||!cloudName)return;const asset=cloudinaryAsset(media.url,media.resourceType);if(!asset)return;const timestamp=Math.floor(Date.now()/1000);const signature=crypto.createHash('sha1').update(`public_id=${asset.publicId}&timestamp=${timestamp}${apiSecret}`).digest('hex');const form=new URLSearchParams({public_id:asset.publicId,timestamp:String(timestamp),api_key:apiKey,signature});try{const response=await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/${asset.resourceType}/destroy`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form});if(!response.ok){const body=await response.text();console.error('Cloudinary cleanup failed:',body)}}catch(error){console.error('Cloudinary cleanup failed:',error.message)}}
async function validateCampaignCause(status,causeId){if(!['active','completed'].includes(status))return null;if(!causeId)return 'Choose a published cause before making this campaign active or completed.';const cause=await Cause.findById(causeId).select('status').lean().catch(()=>null);if(!cause)return 'The selected cause no longer exists.';if(cause.status!=='published')return 'Active and completed campaigns must be linked to a published cause.';return null}
async function validateCauseStatusChange(causeId,nextStatus){if(nextStatus==='published')return null;const linked=await Campaign.countDocuments({cause:causeId,status:{$in:['active','completed']}});if(!linked)return null;return `This cause is linked to ${linked} active or completed campaign${linked===1?'':'s'}. Reassign or pause/archive those campaigns before changing the cause status.`}
async function reconcileDonorAggregates(){
  const [aggregates,existingDonors]=await Promise.all([
    Donation.aggregate([
      {$match:{status:'paid',email:{$nin:['',null]}}},
      {$sort:{paidAt:-1,createdAt:-1}},
      {$group:{_id:'$email',totalDonated:{$sum:'$amount'},donationCount:{$sum:1},lastDonationAt:{$max:'$paidAt'},name:{$first:'$donorName'},phone:{$first:'$phone'}}}
    ]),
    Donor.find().select('_id email totalDonated donationCount lastDonationAt').lean()
  ])
  const totals=new Map(aggregates.map(item=>[normalizeEmail(item._id),item]))
  const operations=[]
  const existingEmails=new Set()
  for(const donor of existingDonors){
    const email=normalizeEmail(donor.email)
    existingEmails.add(email)
    const aggregate=totals.get(email)
    const next={totalDonated:Number(aggregate?.totalDonated||0),donationCount:Number(aggregate?.donationCount||0),lastDonationAt:aggregate?.lastDonationAt||null}
    const currentLast=donor.lastDonationAt?new Date(donor.lastDonationAt).getTime():0
    const nextLast=next.lastDonationAt?new Date(next.lastDonationAt).getTime():0
    if(Number(donor.totalDonated||0)!==next.totalDonated||Number(donor.donationCount||0)!==next.donationCount||currentLast!==nextLast){operations.push({updateOne:{filter:{_id:donor._id},update:{$set:next}}})}
  }
  for(const aggregate of aggregates){
    const email=normalizeEmail(aggregate._id)
    if(existingEmails.has(email))continue
    operations.push({updateOne:{filter:{email},update:{$setOnInsert:{email,name:aggregate.name||'Donor',phone:aggregate.phone||'',status:'active'},$set:{totalDonated:Number(aggregate.totalDonated||0),donationCount:Number(aggregate.donationCount||0),lastDonationAt:aggregate.lastDonationAt||null}},upsert:true}})
  }
  if(operations.length)await Donor.bulkWrite(operations,{ordered:false})
}
async function bootstrapAdmin(email,password){const envEmail=normalizeEmail(process.env.ADMIN_EMAIL);if(!envEmail||!process.env.ADMIN_PASSWORD||email!==envEmail||password!==process.env.ADMIN_PASSWORD)return null;return AdminAccount.findOneAndUpdate({email},{$setOnInsert:{email,passwordHash:await bcrypt.hash(password,12),status:'active'}},{new:true,upsert:true,setDefaultsOnInsert:true})}
async function sendResetEmail(email,resetUrl){if(!process.env.RESEND_API_KEY||!process.env.ADMIN_FROM_EMAIL)return false;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.ADMIN_FROM_EMAIL,to:[email],subject:'RB Charity Foundation admin password reset',html:`<p>A password reset was requested for the RB Charity Foundation admin account.</p><p><a href="${resetUrl}">Reset admin password</a></p><p>This link expires in 30 minutes. If you did not request this, you can ignore this email.</p>`})});return response.ok}
router.post('/login',async(req,res)=>{const email=normalizeEmail(req.body.email),password=String(req.body.password||'');const secret=process.env.JWT_SECRET;if(!secret)return res.status(503).json({success:false,message:'JWT_SECRET is not configured on the server.'});let admin=await AdminAccount.findOne({email});if(!admin)admin=await bootstrapAdmin(email,password);if(!admin||admin.status!=='active'||!await bcrypt.compare(password,admin.passwordHash))return res.status(401).json({success:false,message:'Incorrect admin email or password.'});admin.lastLoginAt=new Date();await admin.save();const token=jwt.sign({role:'admin',sub:String(admin._id),email:admin.email},secret,{expiresIn:'8h'});res.json({success:true,token,admin:{email:admin.email}})})
router.post('/forgot-password',async(req,res)=>{const email=normalizeEmail(req.body.email);let admin=await AdminAccount.findOne({email});if(!admin&&email===normalizeEmail(process.env.ADMIN_EMAIL)&&process.env.ADMIN_PASSWORD)admin=await bootstrapAdmin(email,process.env.ADMIN_PASSWORD);let resetUrl='';if(admin&&admin.status==='active'){const rawToken=crypto.randomBytes(32).toString('hex');admin.resetTokenHash=hashResetToken(rawToken);admin.resetTokenExpiresAt=new Date(Date.now()+30*60*1000);await admin.save();const clientUrl=(process.env.CLIENT_URL||'http://localhost:5173').replace(/\/$/,'');resetUrl=`${clientUrl}/admin/reset-password?token=${encodeURIComponent(rawToken)}&email=${encodeURIComponent(admin.email)}`;try{await sendResetEmail(admin.email,resetUrl)}catch(error){console.error('Admin reset email failed:',error.message)}}const payload={success:true,message:'If that admin email exists, a password reset link has been prepared.'};if(process.env.NODE_ENV!=='production'&&resetUrl)payload.devResetUrl=resetUrl;res.json(payload)})
router.post('/reset-password',async(req,res)=>{const email=normalizeEmail(req.body.email),token=String(req.body.token||''),password=String(req.body.password||'');if(password.length<8)return res.status(400).json({success:false,message:'New password must be at least 8 characters.'});const admin=await AdminAccount.findOne({email,resetTokenHash:hashResetToken(token),resetTokenExpiresAt:{$gt:new Date()},status:'active'});if(!admin)return res.status(400).json({success:false,message:'This reset link is invalid or has expired.'});admin.passwordHash=await bcrypt.hash(password,12);admin.passwordChangedAt=new Date();admin.resetTokenHash='';admin.resetTokenExpiresAt=null;await admin.save();try{await ActivityLog.create({actor:admin.email,action:'password-reset',resource:'admin-security',resourceId:String(admin._id),details:'Admin password reset completed.'})}catch{}res.json({success:true,message:'Password reset successfully. You can now sign in.'})})
router.use(requireAdmin)
router.get('/me',(req,res)=>res.json({success:true,admin:{email:req.admin.email}}))
router.post('/change-password',async(req,res)=>{const currentPassword=String(req.body.currentPassword||''),newPassword=String(req.body.newPassword||'');if(newPassword.length<8)return res.status(400).json({success:false,message:'New password must be at least 8 characters.'});const admin=await AdminAccount.findById(req.admin.id);if(!admin||!await bcrypt.compare(currentPassword,admin.passwordHash))return res.status(400).json({success:false,message:'Current password is incorrect.'});if(await bcrypt.compare(newPassword,admin.passwordHash))return res.status(400).json({success:false,message:'Choose a password different from the current password.'});admin.passwordHash=await bcrypt.hash(newPassword,12);admin.passwordChangedAt=new Date();await admin.save();await log(req,'password-change','admin-security',admin._id,'Admin changed password from settings.');res.json({success:true,message:'Password changed successfully.'})})
router.get('/dashboard',async(_req,res)=>{const [donations,donors,volunteers,partners,messages,campaigns,causes,stories]=await Promise.all([Donation.find().sort({createdAt:-1}).lean(),Donor.countDocuments(),Volunteer.countDocuments(),Partner.countDocuments(),ContactMessage.countDocuments(),Campaign.countDocuments(),Cause.countDocuments(),Story.countDocuments()]);const paid=donations.filter(x=>x.status==='paid'),pending=donations.filter(x=>x.status==='pending'),failed=donations.filter(x=>x.status==='failed');res.json({success:true,summary:{totalRaised:paid.reduce((s,x)=>s+x.amount,0),donations:paid.length,paymentAttempts:donations.length,pendingPayments:pending.length,failedPayments:failed.length,donors,volunteers,partners,messages,campaigns,causes,stories},recentDonations:paid.slice(0,6)})})
router.get('/:resource',async(req,res)=>{const Model=models[req.params.resource];if(!Model)return res.status(404).json({success:false,message:'Unknown admin resource.'});if(req.params.resource==='donors')await reconcileDonorAggregates();let query=Model.find().sort({createdAt:-1}).limit(300);if(req.params.resource==='campaigns')query=query.populate('cause','name slug status');const items=await query.lean();res.json({success:true,items})})
router.post('/:resource',async(req,res)=>{const Model=models[req.params.resource];if(!Model||!creatable.includes(req.params.resource))return res.status(405).json({success:false,message:'Creation is not supported for this resource.'});const body={...req.body};if(req.params.resource==='campaigns'){delete body.raisedAmount;const causeError=await validateCampaignCause(body.status||'draft',body.cause);if(causeError)return res.status(400).json({success:false,message:causeError})}const item=await Model.create(body);await log(req,'create',req.params.resource,item._id);res.status(201).json({success:true,item})})
router.patch('/:resource/:id',async(req,res)=>{const Model=models[req.params.resource];if(!Model)return res.status(404).json({success:false,message:'Unknown admin resource.'});if(req.params.resource==='donations')return res.status(405).json({success:false,message:'Donation payment records are read-only. Payment status is controlled by verified gateway events.'});const body={...req.body};if(body.status&&allowedStatuses[req.params.resource]&&!allowedStatuses[req.params.resource].includes(body.status))return res.status(400).json({success:false,message:'Invalid status.'});if(req.params.resource==='donors'){delete body.totalDonated;delete body.donationCount;delete body.lastDonationAt}if(req.params.resource==='campaigns')delete body.raisedAmount;const previous=await Model.findById(req.params.id).lean();if(!previous)return res.status(404).json({success:false,message:'Record not found.'});if(req.params.resource==='campaigns'){const nextStatus=body.status??previous.status,nextCause=body.cause!==undefined?body.cause:previous.cause;const causeError=await validateCampaignCause(nextStatus,nextCause);if(causeError)return res.status(400).json({success:false,message:causeError})}if(req.params.resource==='causes'){const nextStatus=body.status??previous.status;const relationshipError=await validateCauseStatusChange(previous._id,nextStatus);if(relationshipError)return res.status(409).json({success:false,message:relationshipError})}const oldMedia=cmsMedia(previous,req.params.resource);const item=await Model.findByIdAndUpdate(req.params.id,body,{new:true,runValidators:true});const newMedia=cmsMedia(item,req.params.resource);if(oldMedia?.url&&oldMedia.url!==newMedia?.url)void destroyCloudinaryAsset(oldMedia);await log(req,'update',req.params.resource,item._id);res.json({success:true,item})})
router.delete('/:resource/:id',async(req,res)=>{if(req.params.resource==='activity')return res.status(405).json({success:false,message:'Activity logs cannot be deleted from the admin UI.'});if(req.params.resource==='donations')return res.status(405).json({success:false,message:'Donation payment records cannot be deleted from the admin UI.'});const Model=models[req.params.resource];if(!Model)return res.status(404).json({success:false,message:'Unknown admin resource.'});if(req.params.resource==='causes'){const linked=await Campaign.countDocuments({cause:req.params.id});if(linked)return res.status(409).json({success:false,message:`This cause is linked to ${linked} campaign${linked===1?'':'s'}. Reassign or delete those campaigns before deleting the cause.`})}const item=await Model.findByIdAndDelete(req.params.id);if(!item)return res.status(404).json({success:false,message:'Record not found.'});const media=cmsMedia(item,req.params.resource);if(media?.url)void destroyCloudinaryAsset(media);await log(req,'delete',req.params.resource,req.params.id);res.json({success:true})})
export default router
