import { BarChart3, LogOut, Plus, ShieldCheck, Trash2, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, Navigate, Outlet, useLocation, useNavigate } from 'react-router-dom'
import CustomSelect from '../components/form/CustomSelect'

const API='/api/admin'
const input='w-full rounded-2xl border border-rb-100 bg-white px-4 py-3.5 text-rb-900 outline-none transition focus:border-gold focus:ring-4 focus:ring-gold/10'
const getToken=()=>sessionStorage.getItem('rbAdminToken')||''
const clearToken=()=>{sessionStorage.removeItem('rbAdminToken');localStorage.removeItem('rbAdminToken')}
async function request(path,options={}){const token=getToken();const res=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});const data=await res.json();if(!res.ok)throw new Error(data.message||'Request failed');return data}

export function AdminGuard(){const [state,setState]=useState('checking');useEffect(()=>{localStorage.removeItem('rbAdminToken');const token=getToken();if(!token){setState('denied');return}request('/me').then(()=>setState('allowed')).catch(()=>{clearToken();setState('denied')})},[]);if(state==='checking')return <div className="grid min-h-screen place-items-center bg-rb-50"><div className="rounded-3xl bg-white px-8 py-6 font-black text-rb-900 shadow-sm">Verifying admin session…</div></div>;if(state==='denied')return <Navigate to="/admin/login" replace/>;return <Outlet/>}

export function AdminLoginPage(){const navigate=useNavigate();const [form,setForm]=useState({email:'',password:''});const [state,setState]=useState({busy:false,error:''});useEffect(()=>{clearToken()},[]);async function submit(e){e.preventDefault();setState({busy:true,error:''});try{const data=await request('/login',{method:'POST',body:JSON.stringify(form)});sessionStorage.setItem('rbAdminToken',data.token);navigate('/admin/dashboard',{replace:true})}catch(error){setState({busy:false,error:error.message});return}setState({busy:false,error:''})}return <div className="min-h-screen bg-rb-900 px-5 py-16 text-white"><div className="mx-auto max-w-md"><Link to="/" className="text-sm font-black text-white/70">← Back to website</Link><div className="mt-7 rounded-[2rem] bg-white p-7 text-rb-900 shadow-2xl"><ShieldCheck size={38} className="text-rb-700"/><h1 className="mt-5 text-3xl font-black">Foundation admin</h1><p className="mt-2 text-slate-600">Authorised administrators only.</p><form onSubmit={submit} className="mt-7 space-y-4"><input className={input} type="email" placeholder="Admin email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input className={input} type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/>{state.error&&<ErrorBox text={state.error}/>}<button disabled={state.busy} className="w-full rounded-full bg-gold px-5 py-3.5 font-black text-rb-900 disabled:opacity-50">{state.busy?'Signing in…':'Sign in'}</button></form></div></div></div>}

const nav=[['Dashboard','/admin/dashboard'],['Campaigns','/admin/campaigns'],['Causes','/admin/causes'],['Donations','/admin/donations'],['Donors','/admin/donors'],['Volunteers','/admin/volunteers'],['Partners','/admin/partners'],['Stories','/admin/stories'],['Messages','/admin/messages'],['Gallery','/admin/gallery'],['Reports','/admin/reports'],['Website content','/admin/content'],['Settings','/admin/settings'],['Activity','/admin/activity']]
function AdminShell({children}){const loc=useLocation(),navigate=useNavigate();const logout=()=>{clearToken();navigate('/admin/login',{replace:true})};return <div className="min-h-screen bg-rb-50 text-rb-900"><header className="sticky top-0 z-30 border-b border-rb-100 bg-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-5 py-5"><Link to="/admin/dashboard" className="font-black">RB CHARITY ADMIN</Link><button type="button" onClick={logout} className="inline-flex shrink-0 items-center gap-2 rounded-full bg-rb-900 px-4 py-2 text-sm font-black text-white transition hover:-translate-y-0.5"><LogOut size={16}/>Logout</button></div></header><div className="mx-auto grid max-w-[1500px] gap-7 px-5 py-8 xl:grid-cols-[240px_1fr]"><aside className="h-fit rounded-[1.7rem] bg-rb-900 p-3 text-white">{nav.map(([label,path])=><Link key={path} to={path} className={`block rounded-2xl px-4 py-3 text-sm font-bold transition ${loc.pathname===path?'bg-gold text-rb-900':'text-white/65 hover:bg-white/10 hover:text-white'}`}>{label}</Link>)}</aside><main className="min-w-0">{children}</main></div></div>}

function useAdmin(path){const [state,setState]=useState({loading:true,data:null,error:''});const load=()=>{setState(s=>({...s,loading:true}));request(path).then(data=>setState({loading:false,data,error:''})).catch(error=>{if(/login|required|expired|session/i.test(error.message))clearToken();setState({loading:false,data:null,error:error.message})})};useEffect(load,[path]);return {...state,reload:load}}
const Loading=()=> <div className="rounded-3xl bg-white p-8 font-bold shadow-sm">Loading admin data…</div>

export function AdminDashboardPage(){const s=useAdmin('/dashboard');return <AdminShell>{s.loading?<Loading/>:s.error?<ErrorBox text={s.error}/>:<><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-rb-600">Operations</p><h1 className="mt-2 text-4xl font-black">Admin dashboard</h1></div><BarChart3 className="text-rb-600" size={34}/></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(s.data?.summary||{}).map(([key,value])=><div key={key} className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-xs font-black uppercase tracking-[.12em] text-slate-500">{key.replace(/([A-Z])/g,' $1')}</p><p className="mt-2 text-3xl font-black">{key==='totalRaised'?`₹${Number(value).toLocaleString('en-IN')}`:value}</p></div>)}</div><section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Recent donations</h2><div className="mt-5 space-y-3">{(s.data?.recentDonations||[]).map(item=><div key={item._id} className="flex flex-col gap-2 rounded-2xl border border-rb-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">{item.donorName}</p><p className="text-sm text-slate-500">{item.email} · {item.status}</p></div><p className="text-xl font-black">₹{Number(item.amount).toLocaleString('en-IN')}</p></div>)}</div></section></>}</AdminShell>}

const configs={campaigns:{title:'Campaigns',primary:'title',secondary:'summary',statuses:['draft','active','completed','paused','archived'],createFields:['title','slug','summary','description','goalAmount','status']},causes:{title:'Causes',primary:'name',secondary:'summary',statuses:['draft','published','archived'],createFields:['name','slug','summary','description','status']},donations:{title:'Donations',primary:'donorName',secondary:'email',statuses:['pending','paid','failed']},donors:{title:'Donors',primary:'name',secondary:'email',statuses:['active','blocked','deleted']},volunteers:{title:'Volunteers',primary:'name',secondary:'email',statuses:['new','reviewing','approved','assigned','inactive']},partners:{title:'Partners',primary:'organisation',secondary:'contactName',statuses:['new','contacted','proposal','active','closed']},stories:{title:'Stories',primary:'title',secondary:'excerpt',statuses:['draft','published','archived'],createFields:['title','slug','excerpt','content','status']},messages:{title:'Messages',primary:'name',secondary:'subject',statuses:['new','read','replied','archived']},gallery:{title:'Gallery',primary:'title',secondary:'caption',statuses:['draft','published','archived'],createFields:['title','image','category','caption','status']},reports:{title:'Reports',primary:'title',secondary:'summary',statuses:['draft','published','archived'],createFields:['title','type','year','fileUrl','summary','status']},content:{title:'Website content',primary:'title',secondary:'value',createFields:['key','title','value','group']},settings:{title:'Foundation settings',primary:'key',secondary:'value',createFields:['key','value','group']},activity:{title:'Activity log',primary:'action',secondary:'resource'}}

export function AdminResourcePage({resource}){const c=configs[resource],s=useAdmin(`/${resource}`);const [del,setDel]=useState(null),[create,setCreate]=useState(false),[error,setError]=useState('');async function patch(item,status){try{await request(`/${resource}/${item._id}`,{method:'PATCH',body:JSON.stringify({status})});s.reload()}catch(e){setError(e.message)}}async function remove(){try{await request(`/${resource}/${del._id}`,{method:'DELETE'});setDel(null);s.reload()}catch(e){setError(e.message);setDel(null)}}return <AdminShell>{s.loading?<Loading/>:s.error?<ErrorBox text={s.error}/>:<><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-rb-600">Management</p><h1 className="mt-2 text-4xl font-black">{c.title}</h1><p className="mt-2 text-slate-500">{s.data?.items?.length||0} records</p></div>{c.createFields&&<button onClick={()=>setCreate(true)} className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 font-black"><Plus size={17}/>Add new</button>}</div>{error&&<ErrorBox text={error}/>}<div className="mt-7 overflow-hidden rounded-3xl bg-white shadow-sm"><div className="divide-y divide-rb-100">{(s.data?.items||[]).length?s.data.items.map(item=><div key={item._id} className="grid gap-4 p-5 lg:grid-cols-[1fr_210px_auto] lg:items-center"><div className="min-w-0"><p className="truncate font-black">{String(item[c.primary]??'Untitled')}</p><p className="mt-1 truncate text-sm text-slate-500">{String(item[c.secondary]??item.email??item.phone??'—')}</p>{resource==='donations'&&<p className="mt-1 font-black">₹{Number(item.amount).toLocaleString('en-IN')}</p>}</div>{c.statuses?<CustomSelect value={item.status||c.statuses[0]} onChange={v=>patch(item,v)} options={c.statuses.map(x=>({value:x,label:x}))}/>:<span className="text-sm text-slate-400">{item.createdAt?new Date(item.createdAt).toLocaleString('en-IN'):'—'}</span>}{resource!=='activity'?<button onClick={()=>setDel(item)} className="grid h-10 w-10 place-items-center rounded-full border border-red-100 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button>:<span/>}</div>):<div className="p-8 text-slate-500">No records yet.</div>}</div></div>{del&&<ConfirmModal onCancel={()=>setDel(null)} onConfirm={remove}/>} {create&&<CreateModal resource={resource} config={c} onClose={()=>setCreate(false)} onCreated={()=>{setCreate(false);s.reload()}}/>}</>}</AdminShell>}

function CreateModal({resource,config,onClose,onCreated}){const initial=Object.fromEntries(config.createFields.map(k=>[k,k==='status'?config.statuses[0]:k==='year'||k==='goalAmount'?0:'']));const [form,setForm]=useState(initial),[error,setError]=useState('');async function submit(e){e.preventDefault();try{await request(`/${resource}`,{method:'POST',body:JSON.stringify(form)});onCreated()}catch(err){setError(err.message)}}return <ModalShell onClose={onClose}><h2 className="text-2xl font-black">Add {config.title.toLowerCase()}</h2><form onSubmit={submit} className="mt-6 space-y-4">{config.createFields.map(key=>key==='status'?<CustomSelect key={key} value={form[key]} onChange={v=>setForm({...form,[key]:v})} options={config.statuses.map(x=>({value:x,label:x}))}/>:key==='description'||key==='content'||key==='value'||key==='summary'||key==='caption'?<textarea key={key} rows={3} className={input} placeholder={key} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input key={key} className={input} type={key==='year'||key==='goalAmount'?'number':'text'} placeholder={key} value={form[key]} onChange={e=>setForm({...form,[key]:key==='year'||key==='goalAmount'?Number(e.target.value):e.target.value})}/>)}{error&&<ErrorBox text={error}/>}<button className="w-full rounded-full bg-rb-900 px-5 py-3 font-black text-white">Create</button></form></ModalShell>}
function ModalShell({children,onClose}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-rb-900/60 p-5 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="relative max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-[2rem] bg-white p-7 shadow-2xl"><button onClick={onClose} className="absolute right-5 top-5 grid h-9 w-9 place-items-center rounded-full bg-rb-50" aria-label="Close modal"><X size={18}/></button>{children}</div></div>}
function ConfirmModal({onCancel,onConfirm}){return <ModalShell onClose={onCancel}><h2 className="text-2xl font-black">Delete this record?</h2><p className="mt-3 text-slate-600">This action permanently removes the selected record.</p><div className="mt-7 flex justify-end gap-3"><button onClick={onCancel} className="rounded-full border border-rb-100 px-5 py-3 font-black">Cancel</button><button onClick={onConfirm} className="rounded-full bg-red-600 px-5 py-3 font-black text-white">Delete</button></div></ModalShell>}
function ErrorBox({text}){return <div className="mt-5 rounded-2xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{text}</div>}
