import { ArrowRight, Eye, Mail, MessageSquareText, Phone, Search, Trash2, UsersRound, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import AdminShell from '../components/admin/AdminShell'
import CustomSelect from '../components/form/CustomSelect'

const API='/api/admin'
const request=async(path,options={})=>{const response=await fetch(`${API}${path}`,{...options,credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.message||'Request failed');return data}

const configs={
  volunteers:{title:'Volunteer Pipeline',description:'Review applications and move volunteers from enquiry to active assignment.',icon:UsersRound,statuses:['new','reviewing','approved','assigned','inactive'],primary:'name',secondary:'email',details:[['email','Email'],['phone','Mobile'],['city','City'],['skills','Skills'],['availability','Availability'],['message','Why they want to volunteer'],['createdAt','Applied']]},
  partners:{title:'Partnership Pipeline',description:'Track organisations from first enquiry through proposal and active partnership.',icon:UsersRound,statuses:['new','contacted','proposal','active','closed'],primary:'organisation',secondary:'contactName',details:[['contactName','Contact person'],['email','Email'],['phone','Mobile'],['type','Organisation type'],['message','Collaboration idea'],['createdAt','Submitted']]},
  messages:{title:'Message Inbox',description:'Review incoming enquiries, respond quickly and archive completed conversations.',icon:MessageSquareText,statuses:['new','read','replied','archived'],primary:'name',secondary:'subject',details:[['email','Email'],['phone','Mobile'],['category','Category'],['subject','Subject'],['message','Message'],['createdAt','Received']]},
}

const format=(key,value)=>{if(value===null||value===undefined||value==='')return '—';if(Array.isArray(value))return value.length?value.join(', '):'—';if(key.endsWith('At'))return new Date(value).toLocaleString('en-IN');return String(value)}
const statusTone=status=>status==='new'?'border-amber-200 bg-amber-50 text-amber-800':status==='active'||status==='assigned'||status==='approved'||status==='replied'?'border-emerald-200 bg-emerald-50 text-emerald-800':status==='inactive'||status==='closed'||status==='archived'?'border-slate-200 bg-slate-50 text-slate-600':'border-blue-200 bg-blue-50 text-blue-800'

export default function AdminEngagementPage({resource}){
  const config=configs[resource],Icon=config.icon
  const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[view,setView]=useState(null),[del,setDel]=useState(null),[saving,setSaving]=useState('')
  const load=async()=>{setLoading(true);setError('');try{const data=await request(`/${resource}`);setItems(data.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[resource])
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return items.filter(item=>(status==='all'||item.status===status)&&(!q||config.details.some(([key])=>format(key,item[key]).toLowerCase().includes(q))||String(item[config.primary]||'').toLowerCase().includes(q)||String(item[config.secondary]||'').toLowerCase().includes(q)))},[items,search,status,config])
  const counts=useMemo(()=>Object.fromEntries(config.statuses.map(s=>[s,items.filter(item=>item.status===s).length])),[items,config])
  async function updateStatus(item,next){setSaving(item._id);setError('');try{const data=await request(`/${resource}/${item._id}`,{method:'PATCH',body:JSON.stringify({status:next})});setItems(current=>current.map(record=>record._id===item._id?data.item:record));setView(current=>current?._id===item._id?data.item:current)}catch(e){setError(e.message)}finally{setSaving('')}}
  async function remove(){if(!del)return;setSaving(del._id);try{await request(`/${resource}/${del._id}`,{method:'DELETE'});setItems(current=>current.filter(item=>item._id!==del._id));if(view?._id===del._id)setView(null);setDel(null)}catch(e){setError(e.message)}finally{setSaving('')}}
  const nextStatus=item=>{const index=config.statuses.indexOf(item.status);return index>=0&&index<config.statuses.length-1?config.statuses[index+1]:null}

  return <AdminShell><div className="min-w-0">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-rb-600">Engagement management</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-black sm:text-4xl"><Icon className="text-rb-600"/>{config.title}</h1><p className="mt-2 max-w-2xl text-slate-500">{config.description}</p></div><div className="rounded-2xl border border-rb-100 bg-white px-5 py-3 text-sm font-bold text-slate-500"><strong className="text-2xl text-rb-900">{items.length}</strong> total records</div></div>
    {error&&<div className="mt-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{config.statuses.map(s=><button key={s} onClick={()=>setStatus(status===s?'all':s)} className={`rounded-2xl border p-4 text-left transition hover:-translate-y-0.5 ${status===s?'border-rb-500 bg-rb-900 text-white shadow-lg':'border-rb-100 bg-white'}`}><p className={`text-xs font-black uppercase tracking-[.12em] ${status===s?'text-white/60':'text-slate-400'}`}>{s}</p><p className="mt-2 text-2xl font-black">{counts[s]||0}</p></button>)}</div>
    <section className="mt-5 rounded-3xl bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_220px]"><label className="relative"><Search size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${resource}...`} className="w-full rounded-2xl border border-rb-100 bg-rb-50/50 py-3.5 pl-11 pr-4 outline-none focus:border-gold focus:ring-4 focus:ring-gold/10"/></label><CustomSelect value={status} onChange={setStatus} options={[{value:'all',label:'All statuses'},...config.statuses.map(s=>({value:s,label:s}))]}/></div></section>
    <div className="mt-5 overflow-hidden rounded-3xl bg-white shadow-sm">{loading?<div className="p-10 text-center font-bold text-slate-400">Loading records…</div>:filtered.length?<div className="divide-y divide-rb-100">{filtered.map(item=>{const next=nextStatus(item);return <article key={item._id} className="grid gap-4 p-4 sm:p-5 xl:grid-cols-[minmax(0,1fr)_180px_auto] xl:items-center"><button onClick={()=>setView(item)} className="min-w-0 text-left"><div className="flex flex-wrap items-center gap-2"><p className="break-words font-black text-rb-900">{item[config.primary]||'Untitled'}</p><span className={`rounded-full border px-2.5 py-1 text-[11px] font-black uppercase ${statusTone(item.status)}`}>{item.status}</span></div><p className="mt-1 break-words text-sm text-slate-500">{item[config.secondary]||item.email||'—'}</p><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{item.message||item.skills?.join(', ')||'No additional note provided.'}</p></button><CustomSelect disabled={saving===item._id} value={item.status} onChange={value=>updateStatus(item,value)} options={config.statuses.map(s=>({value:s,label:s}))}/><div className="flex flex-wrap gap-2"><button onClick={()=>setView(item)} className="grid h-10 w-10 place-items-center rounded-full border border-rb-100 text-rb-700" aria-label="View details"><Eye size={17}/></button>{item.email&&<a href={`mailto:${item.email}`} className="grid h-10 w-10 place-items-center rounded-full border border-rb-100 text-rb-700" aria-label="Send email"><Mail size={17}/></a>}{item.phone&&<a href={`tel:${item.phone}`} className="grid h-10 w-10 place-items-center rounded-full border border-rb-100 text-rb-700" aria-label="Call"><Phone size={17}/></a>}{next&&<button disabled={saving===item._id} onClick={()=>updateStatus(item,next)} className="inline-flex items-center gap-2 rounded-full bg-rb-900 px-4 py-2 text-xs font-black capitalize text-white disabled:opacity-50">{next}<ArrowRight size={14}/></button>}<button onClick={()=>setDel(item)} className="grid h-10 w-10 place-items-center rounded-full border border-red-100 text-red-600" aria-label="Delete"><Trash2 size={17}/></button></div></article>})}</div>:<div className="p-10 text-center text-slate-500">No records match your filters.</div>}</div>
    {view&&<div className="fixed inset-0 z-[70] flex items-end justify-center bg-rb-900/55 p-0 backdrop-blur-sm sm:items-center sm:p-5"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-[2rem] bg-white p-5 shadow-2xl sm:rounded-[2rem] sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.15em] text-rb-600">Record details</p><h2 className="mt-2 break-words text-2xl font-black">{view[config.primary]}</h2><span className={`mt-3 inline-flex rounded-full border px-3 py-1.5 text-xs font-black uppercase ${statusTone(view.status)}`}>{view.status}</span></div><button onClick={()=>setView(null)} className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-rb-50" aria-label="Close"><X size={19}/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{config.details.map(([key,label])=><div key={key} className={`${key==='message'||key==='skills'?'sm:col-span-2':''} rounded-2xl bg-rb-50/70 p-4`}><p className="text-xs font-black uppercase tracking-[.1em] text-slate-400">{label}</p><p className="mt-2 break-words whitespace-pre-wrap font-semibold leading-6 text-rb-900">{format(key,view[key])}</p></div>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-[1fr_auto_auto] sm:items-center"><CustomSelect value={view.status} onChange={value=>updateStatus(view,value)} options={config.statuses.map(s=>({value:s,label:s}))}/>{view.email&&<a href={`mailto:${view.email}`} className="inline-flex items-center justify-center gap-2 rounded-full bg-rb-900 px-5 py-3 text-sm font-black text-white"><Mail size={16}/>Email</a>}{view.phone&&<a href={`tel:${view.phone}`} className="inline-flex items-center justify-center gap-2 rounded-full bg-gold px-5 py-3 text-sm font-black text-rb-900"><Phone size={16}/>Call</a>}</div></div></div>}
    {del&&<div className="fixed inset-0 z-[80] grid place-items-center bg-rb-900/60 p-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-[2rem] bg-white p-6 shadow-2xl"><h2 className="text-xl font-black">Delete this record?</h2><p className="mt-3 leading-7 text-slate-500">This permanently removes <strong className="text-rb-900">{del[config.primary]}</strong>. Use a closed, archived or inactive status instead when you need to preserve history.</p><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setDel(null)} className="rounded-full border border-rb-100 px-5 py-3 text-sm font-black">Cancel</button><button disabled={saving===del._id} onClick={remove} className="rounded-full bg-red-600 px-5 py-3 text-sm font-black text-white disabled:opacity-50">Delete permanently</button></div></div></div>}
  </div></AdminShell>
}
