import { ArrowLeft, ArrowRight, FileText, ShieldCheck } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { gallerySeed, impactMetrics, reportsSeed, storiesSeed, transparencySteps } from '../data/contentSeed'

const shell='mx-auto w-full max-w-7xl px-5 sm:px-6 lg:px-8'

function Hero({eyebrow,title,copy}){return <section className="bg-rb-900 py-20 text-white"><div className={shell}><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{eyebrow}</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-[-.04em] sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/70">{copy}</p></div></section>}

export function ImpactPage(){return <main className="bg-[#f8fbff]"><Hero eyebrow="Impact" title="From contribution to documented change." copy="The impact module connects cause areas, campaigns, field activity and public reporting into one clear story."/><section className="py-16 sm:py-20"><div className={shell}><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{impactMetrics.map(item=><article key={item.label} className="rounded-[2rem] border border-rb-100 bg-white p-6 shadow-sm"><p className="text-3xl font-black text-rb-900">{item.value}</p><h2 className="mt-3 font-black text-rb-900">{item.label}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{item.note}</p></article>)}</div><div className="mt-12 rounded-[2.5rem] bg-rb-900 p-7 text-white sm:p-10"><h2 className="text-3xl font-black">Impact pathway</h2><div className="mt-7 grid gap-4 lg:grid-cols-4">{transparencySteps.map(([n,title,copy])=><div key={n} className="rounded-3xl border border-white/10 bg-white/10 p-5"><span className="text-sm font-black text-gold">{n}</span><h3 className="mt-3 text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-white/65">{copy}</p></div>)}</div><div className="mt-7 flex flex-wrap gap-3"><Link to="/transparency" className="rounded-full bg-gold px-5 py-3 font-black text-rb-900">View transparency</Link><Link to="/reports" className="rounded-full border border-white/20 px-5 py-3 font-black text-white">Reports</Link></div></div></div></section></main>}

export function TransparencyPage(){return <main className="bg-[#f8fbff]"><Hero eyebrow="Transparency" title="A clear trail from funds to field work." copy="The platform is structured to publish how support is received, allocated, used and documented without relying on decorative numbers."/><section className="py-16 sm:py-20"><div className={shell}><div className="grid gap-5 md:grid-cols-2">{transparencySteps.map(([n,title,copy])=><article key={n} className="rounded-[2rem] border border-rb-100 bg-white p-7"><div className="flex items-start gap-5"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-rb-900 font-black text-white">{n}</span><div><h2 className="text-2xl font-black text-rb-900">{title}</h2><p className="mt-3 leading-7 text-slate-600">{copy}</p></div></div></article>)}</div><div className="mt-12 grid gap-5 lg:grid-cols-3">{[['Campaign reporting','Funding goals, allocations and milestone updates stay linked to the campaign.'],['Foundation reporting','Annual and impact reports provide organisation-level transparency.'],['Donor records','Donation history and receipts will give individual contributors their own record trail.']].map(([title,copy])=><div key={title} className="rounded-3xl bg-rb-50 p-6"><ShieldCheck className="text-rb-700"/><h3 className="mt-4 text-xl font-black text-rb-900">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></div>)}</div></div></section></main>}

export function ReportsPage(){return <main className="bg-[#f8fbff]"><Hero eyebrow="Reports & documents" title="Public documents in one place." copy="Annual, impact, governance and transparency documents will be published here as they are approved."/><section className="py-16 sm:py-20"><div className={shell}><div className="space-y-4">{reportsSeed.map(report=><article key={report.title} className="flex flex-col gap-5 rounded-[2rem] border border-rb-100 bg-white p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-rb-50 text-rb-700"><FileText/></span><div><h2 className="text-xl font-black text-rb-900">{report.title}</h2><p className="mt-1 text-sm font-semibold text-rb-600">{report.type} · {report.year}</p><p className="mt-3 max-w-2xl leading-7 text-slate-600">{report.description}</p></div></div><span className="w-fit rounded-full bg-orange-50 px-3 py-1.5 text-xs font-black uppercase tracking-[.14em] text-orange-700">{report.status}</span></article>)}</div></div></section></main>}

export function StoriesPage(){return <main className="bg-[#f8fbff]"><Hero eyebrow="Stories of change" title="People, progress and field updates." copy="Stories connect campaign activity to the people, volunteers and communities behind the work."/><section className="py-16 sm:py-20"><div className={`${shell} grid gap-6 lg:grid-cols-3`}>{storiesSeed.map(story=><article key={story.slug} className="overflow-hidden rounded-[2rem] border border-rb-100 bg-white shadow-sm"><img src={story.image} alt={story.title} className="h-60 w-full object-cover"/><div className="p-6"><p className="text-xs font-black uppercase tracking-[.16em] text-rb-600">{story.category}</p><h2 className="mt-3 text-2xl font-black text-rb-900">{story.title}</h2><p className="mt-3 leading-7 text-slate-600">{story.excerpt}</p><Link to={`/stories/${story.slug}`} className="mt-5 inline-flex items-center gap-2 font-black text-rb-700">Read story <ArrowRight size={17}/></Link></div></article>)}</div></section></main>}

export function StoryDetailsPage(){const {slug}=useParams();const story=storiesSeed.find(item=>item.slug===slug);if(!story)return <main className="bg-[#f8fbff] py-20"><div className={shell}><h1 className="text-3xl font-black text-rb-900">Story not found</h1><Link to="/stories" className="mt-5 inline-flex items-center gap-2 font-black text-rb-700"><ArrowLeft size={17}/> Back to stories</Link></div></main>;return <main className="bg-[#f8fbff]"><section className="relative min-h-[430px] overflow-hidden bg-rb-900"><img src={story.image} alt={story.title} className="absolute inset-0 h-full w-full object-cover opacity-40"/><div className="absolute inset-0 bg-gradient-to-r from-rb-900 via-rb-900/80 to-transparent"/><div className={`${shell} relative py-20 text-white`}><Link to="/stories" className="inline-flex items-center gap-2 text-sm font-black text-white/70"><ArrowLeft size={16}/> Stories</Link><p className="mt-12 text-xs font-black uppercase tracking-[.18em] text-gold">{story.category}</p><h1 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.04em] sm:text-6xl">{story.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/75">{story.excerpt}</p></div></section><section className="py-16 sm:py-20"><div className="mx-auto max-w-3xl px-5 sm:px-6">{story.content.map(paragraph=><p key={paragraph} className="mb-6 text-lg leading-8 text-slate-700">{paragraph}</p>)}</div></section></main>}

export function GalleryPage(){return <main className="bg-[#f8fbff]"><Hero eyebrow="Gallery" title="A visual record of field work." copy="Original photographs from RB Charity Foundation activities and legacy project assets are organised here for campaign and impact storytelling."/><section className="py-16 sm:py-20"><div className={`${shell} grid gap-4 sm:grid-cols-2 lg:grid-cols-3`}>{gallerySeed.map((item,index)=><figure key={`${item.title}-${index}`} className="group relative min-h-72 overflow-hidden rounded-[2rem] bg-rb-900"><img src={item.image} alt={item.title} className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-rb-900/90 via-transparent to-transparent"/><figcaption className="absolute inset-x-0 bottom-0 p-6 text-white"><p className="text-xs font-black uppercase tracking-[.16em] text-gold">{item.category}</p><h2 className="mt-2 text-xl font-black">{item.title}</h2></figcaption></figure>)}</div></section></main>}
