import { Heart, LogOut, ReceiptText, UserRound } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { PageSkeleton } from '../components/system/SystemUI'

const API='/api/donor'
const field='w-full rounded-2xl border border-rb-100 bg-white px-4 py-3.5 outline-none transition focus:border-gold focus:ring-4 focus:ring-gold/10'
const getToken=()=>localStorage.getItem('rbDonorToken')||''
const request=async(path,options={})=>{const res=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(getToken()?{Authorization:`Bearer ${getToken()}`}:{}) ,...(options.headers||{})}});const data=await res.json();if(!res.ok)throw new Error(data.message||'Request failed');return data}

export function DonorAuthPage({mode}){
 const register=mode==='register',navigate=useNavigate(); const [form,setForm]=useState({name:'',email:'',phone:'',password:''});const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const data=await request(register?'/register':'/login',{method:'POST',body:JSON.stringify(form)});localStorage.setItem('rbDonorToken',data.token);navigate('/donor/dashboard')}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <div className="min-h-screen bg-rb-50 px-5 py-16"><div className="mx-auto max-w-md"><Link to="/" className="text-sm font-black text-rb-700">← Back to foundation</Link><div className="mt-6 rounded-[2rem] border border-rb-100 bg-white p-7 shadow-xl"><span className="text-xs font-black uppercase tracking-[.18em] text-rb-600">Donor account</span><h1 className="mt-3 text-3xl font-black text-rb-900">{register?'Create your account':'Welcome back'}</h1><p className="mt-2 text-slate-600">{register?'Keep your donation history and supported campaigns together.':'Sign in to view your contribution history.'}</p><form onSubmit={submit} className="mt-7 space-y-4">{register&&<><input className={field} placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={field} placeholder="Mobile number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></>}<input className={field} type="email" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className={field} type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<button disabled={busy} className="w-full rounded-full bg-rb-900 px-5 py-3.5 font-black text-white transition hover:-translate-y-0.5 disabled:opacity-50">{busy?'Please wait…':register?'Create account':'Sign in'}</button></form><p className="mt-5 text-center text-sm text-slate-600">{register?'Already registered?':'New donor?'} <Link className="font-black text-rb-700" to={register?'/donor/login':'/donor/register'}>{register?'Sign in':'Create account'}</Link></p></div></div></div>
}

const nav=[['Dashboard','/donor/dashboard'],['My donations','/donor/donations'],['Receipts','/donor/receipts'],['Supported campaigns','/donor/campaigns'],['Profile','/donor/profile']]
function DonorShell({children}){const navigate=useNavigate(),loc=useLocation();const logout=()=>{localStorage.removeItem('rbDonorToken');navigate('/donor/login')};return <div className="min-h-screen bg-rb-50"><header className="border-b border-rb-100 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link to="/" className="font-black text-rb-900">RB CHARITY FOUNDATION</Link><button onClick={logout} className="flex items-center gap-2 rounded-full bg-rb-50 px-4 py-2 text-sm font-black text-rb-800"><LogOut size={16}/> Logout</button></div></header><div className="mx-auto grid max-w-7xl gap-7 px-5 py-8 lg:grid-cols-[230px_1fr]"><aside className="h-fit rounded-3xl bg-rb-900 p-3 text-white">{nav.map(([label,path])=><Link key={path} to={path} className={`block rounded-2xl px-4 py-3 font-bold transition ${loc.pathname===path?'bg-gold text-rb-900':'text-white/70 hover:bg-white/10 hover:text-white'}`}>{label}</Link>)}</aside><main>{children}</main></div></div>}

function useProtected(path){const [state,setState]=useState({loading:true,data:null,error:''});useEffect(()=>{if(!getToken()){setState({loading:false,data:null,error:'unauthorized'});return}request(path).then(data=>setState({loading:false,data,error:''})).catch(err=>{if(/session|log in/i.test(err.message))localStorage.removeItem('rbDonorToken');setState({loading:false,data:null,error:err.message})})},[path]);return state}
const Loading=()=> <PageSkeleton cards={4}/>
const Money=({value})=><>₹{Number(value||0).toLocaleString('en-IN')}</>

export function DonorDashboardPage(){const s=useProtected('/dashboard');if(s.error==='unauthorized')return <Navigate to="/donor/login" replace/>;return <DonorShell>{s.loading?<Loading/>:<><h1 className="text-4xl font-black text-rb-900">Your impact dashboard</h1><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Total contributed',<Money value={s.data.summary.totalContributed}/>],['Donation records',s.data.summary.totalDonations],['Completed donations',s.data.summary.paidDonations],['Campaigns supported',s.data.summary.campaignsSupported]].map(([a,b])=><div key={a} className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-sm font-bold text-slate-500">{a}</p><p className="mt-2 text-3xl font-black text-rb-900">{b}</p></div>)}</div><DonationList items={s.data.recent} title="Recent donations"/></>}</DonorShell>}
function DonationList({items=[],title='My donations'}){return <section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black text-rb-900">{title}</h2><div className="mt-5 space-y-3">{items.length?items.map(item=><div key={item._id} className="flex flex-col gap-3 rounded-2xl border border-rb-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black text-rb-900">{item.cause||'General Fund'}</p><p className="text-sm text-slate-500">{new Date(item.createdAt).toLocaleDateString('en-IN')} · {item.status}</p></div><p className="text-xl font-black text-rb-800"><Money value={item.amount}/></p></div>):<p className="text-slate-500">No donation records yet.</p>}</div></section>}
export function DonorDonationsPage(){const s=useProtected('/donations');if(s.error==='unauthorized')return <Navigate to="/donor/login" replace/>;return <DonorShell>{s.loading?<Loading/>:<><h1 className="text-4xl font-black text-rb-900">My donations</h1><DonationList items={s.data.donations}/></>}</DonorShell>}
export function DonorReceiptsPage(){const s=useProtected('/donations');if(s.error==='unauthorized')return <Navigate to="/donor/login" replace/>;const paid=s.data?.donations?.filter(x=>x.status==='paid')||[];return <DonorShell>{s.loading?<Loading/>:<><h1 className="text-4xl font-black text-rb-900">Receipts</h1><p className="mt-3 text-slate-600">Receipts will be downloadable here once payment and receipt generation are connected.</p><DonationList items={paid} title="Completed contributions"/></>}</DonorShell>}
export function DonorCampaignsPage(){const s=useProtected('/donations');if(s.error==='unauthorized')return <Navigate to="/donor/login" replace/>;const campaigns=[...new Map((s.data?.donations||[]).filter(x=>x.campaignSlug).map(x=>[x.campaignSlug,x])).values()];return <DonorShell>{s.loading?<Loading/>:<><h1 className="text-4xl font-black text-rb-900">Supported campaigns</h1><div className="mt-7 grid gap-4 md:grid-cols-2">{campaigns.length?campaigns.map(x=><Link to={`/campaigns/${x.campaignSlug}`} key={x.campaignSlug} className="rounded-3xl bg-white p-6 shadow-sm transition hover:-translate-y-1"><Heart className="text-rb-700"/><h2 className="mt-4 text-xl font-black text-rb-900">{x.cause}</h2><p className="mt-2 text-slate-500">View campaign</p></Link>):<p className="text-slate-500">You have not supported a campaign yet.</p>}</div></>}</DonorShell>}
export function DonorProfilePage(){const s=useProtected('/me');const [form,setForm]=useState(null),[message,setMessage]=useState('');useEffect(()=>{if(s.data?.donor)setForm({name:s.data.donor.name,phone:s.data.donor.phone||''})},[s.data]);if(s.error==='unauthorized')return <Navigate to="/donor/login" replace/>;const save=async e=>{e.preventDefault();const d=await request('/me',{method:'PATCH',body:JSON.stringify(form)});setForm({name:d.donor.name,phone:d.donor.phone||''});setMessage('Profile updated.')};return <DonorShell>{s.loading||!form?<Loading/>:<><h1 className="text-4xl font-black text-rb-900">Profile</h1><form onSubmit={save} className="mt-7 max-w-xl space-y-4 rounded-3xl bg-white p-7 shadow-sm"><UserRound className="text-rb-700"/><input className={field} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className={field} value={form.phone} placeholder="Mobile number" onChange={e=>setForm({...form,phone:e.target.value})}/><p className="text-sm text-slate-500">Email: {s.data.donor.email}</p>{message&&<p className="text-sm font-bold text-green-700">{message}</p>}<button className="rounded-full bg-rb-900 px-5 py-3 font-black text-white">Save changes</button></form></>}</DonorShell>}
