import { AlertTriangle, Download, ExternalLink, FileText, ImageOff, PlayCircle, RefreshCw } from 'lucide-react'
import { useEffect, useState } from 'react'
import { PageSkeleton } from '../components/system/SystemUI'

const shell='mx-auto w-full max-w-7xl px-5 sm:px-6 lg:px-8'
function Hero({eyebrow,title,copy}){return <section className="bg-rb-900 py-20 text-white"><div className={shell}><p className="text-xs font-black uppercase tracking-[.18em] text-gold">{eyebrow}</p><h1 className="mt-4 max-w-4xl text-4xl font-black tracking-[-.04em] sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/70">{copy}</p></div></section>}
function usePublicResource(resource){const [reloadKey,setReloadKey]=useState(0),[state,setState]=useState({loading:true,items:[],error:''});useEffect(()=>{let active=true;setState(current=>({...current,loading:true,error:''}));fetch(`/api/public/${resource}`).then(async response=>{const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||`Unable to load ${resource}.`);if(active)setState({loading:false,items:data.items||[],error:''})}).catch(error=>{if(active)setState({loading:false,items:[],error:error.message||`Unable to load ${resource}.`})});return()=>{active=false}},[resource,reloadKey]);return {...state,retry:()=>setReloadKey(key=>key+1)}}
function LoadError({message,onRetry}){return <div className="rounded-[2rem] border border-red-100 bg-white p-8 text-center shadow-sm"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-red-50 text-red-600"><AlertTriangle size={22}/></div><h2 className="mt-4 text-xl font-black text-rb-900">Unable to load this content</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-600">{message}</p><button type="button" onClick={onRetry} className="mt-5 inline-flex items-center gap-2 rounded-full bg-rb-900 px-5 py-3 text-sm font-black text-white transition hover:-translate-y-0.5"><RefreshCw size={16}/>Try again</button></div>}

export function DynamicReportsPage(){
  const state=usePublicResource('reports')
  if(state.loading)return <main className="bg-[#f8fbff]"><Hero eyebrow="Reports & documents" title="Public documents in one place." copy="Annual, impact, governance and transparency documents are published here as they are approved."/><div className={`${shell} py-16`}><PageSkeleton cards={4}/></div></main>
  return <main className="bg-[#f8fbff]"><Hero eyebrow="Reports & documents" title="Public documents in one place." copy="Annual, impact, governance and transparency documents are published here as they are approved."/><section className="py-16 sm:py-20"><div className={shell}>{state.error?<LoadError message={state.error} onRetry={state.retry}/>:state.items.length?<div className="space-y-4">{state.items.map(report=><article key={report._id||report.title} className="rounded-[2rem] border border-rb-100 bg-white p-5 shadow-sm sm:p-6"><div className="flex min-w-0 flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-rb-50 text-rb-700"><FileText/></span><div className="min-w-0"><h2 className="break-words text-xl font-black text-rb-900">{report.title}</h2><p className="mt-1 break-words text-sm font-semibold text-rb-600">{report.type||'Report'}{report.year?` · ${report.year}`:''}</p>{report.summary&&<p className="mt-3 max-w-2xl break-words leading-7 text-slate-600">{report.summary}</p>}</div></div>{report.fileUrl?<div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row"><a href={report.fileUrl} target="_blank" rel="noopener noreferrer" className="inline-flex w-full items-center justify-center gap-2 rounded-full bg-rb-900 px-4 py-2.5 text-sm font-black text-white transition hover:-translate-y-0.5 sm:w-auto"><ExternalLink size={16}/>View report</a><a href={report.fileUrl} download className="inline-flex w-full items-center justify-center gap-2 rounded-full border border-rb-100 bg-white px-4 py-2.5 text-sm font-black text-rb-800 transition hover:bg-rb-50 sm:w-auto"><Download size={16}/>Download</a></div>:<span className="w-fit shrink-0 rounded-full bg-orange-50 px-3 py-1.5 text-xs font-black uppercase tracking-[.14em] text-orange-700">Document unavailable</span>}</div></article>)}</div>:<div className="rounded-[2rem] border border-dashed border-rb-200 bg-white p-10 text-center"><FileText className="mx-auto text-rb-500"/><h2 className="mt-4 text-2xl font-black text-rb-900">No reports published yet</h2><p className="mt-2 text-slate-600">Approved foundation reports will appear here automatically.</p></div>}</div></section></main>
}

export function DynamicGalleryPage(){
  const state=usePublicResource('gallery')
  if(state.loading)return <main className="bg-[#f8fbff]"><Hero eyebrow="Gallery" title="A visual record of field work." copy="Foundation activities, campaigns and community work are documented here."/><div className={`${shell} py-16`}><PageSkeleton cards={6}/></div></main>
  return <main className="bg-[#f8fbff]"><Hero eyebrow="Gallery" title="A visual record of field work." copy="Foundation activities, campaigns and community work are documented here."/><section className="py-16 sm:py-20"><div className={shell}>{state.error?<LoadError message={state.error} onRetry={state.retry}/>:state.items.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{state.items.map((item,index)=>{const mediaType=item.mediaType||'image',mediaUrl=item.mediaUrl||item.image;return <figure key={item._id||`${item.title}-${index}`} className="group relative min-h-72 overflow-hidden rounded-[2rem] bg-rb-900">{mediaType==='video'&&mediaUrl?<video src={mediaUrl} controls preload="metadata" className="absolute inset-0 h-full w-full object-cover" aria-label={item.title}/>:mediaUrl?<img src={mediaUrl} alt={item.title||'RB Charity Foundation activity'} className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="absolute inset-0 grid place-items-center bg-rb-800 text-white/40"><ImageOff size={36}/></div>}<div className={`pointer-events-none absolute inset-0 bg-gradient-to-t from-rb-900/90 via-transparent to-transparent ${mediaType==='video'?'opacity-70':''}`}/>{mediaType==='video'&&<div className="pointer-events-none absolute right-5 top-5 grid h-11 w-11 place-items-center rounded-full bg-white/90 text-rb-900 shadow"><PlayCircle size={22}/></div>}<figcaption className="pointer-events-none absolute inset-x-0 bottom-0 p-6 text-white"><p className="text-xs font-black uppercase tracking-[.16em] text-gold">{item.category||'Foundation work'}</p><h2 className="mt-2 text-xl font-black">{item.title||'Foundation activity'}</h2>{item.caption&&<p className="mt-2 text-sm text-white/70">{item.caption}</p>}</figcaption></figure>})}</div>:<div className="rounded-[2rem] border border-dashed border-rb-200 bg-white p-10 text-center"><ImageOff className="mx-auto text-rb-500"/><h2 className="mt-4 text-2xl font-black text-rb-900">No gallery items published yet</h2><p className="mt-2 text-slate-600">Published images and videos from the admin panel will appear here automatically.</p></div>}</div></section></main>
}
