import { CheckCircle2, Loader2, Send, Sparkles, Users, Building2, MessageCircle, ArrowRight } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import CustomSelect from '../components/form/CustomSelect'
import { charityMedia } from '../data/charityMedia'

const shell='mx-auto w-full max-w-7xl px-5 sm:px-6 lg:px-8'
const input='w-full rounded-2xl border border-rb-100 bg-white px-4 py-3.5 text-rb-900 shadow-sm outline-none transition duration-300 placeholder:text-slate-400 hover:border-rb-200 focus:border-rb-400 focus:ring-4 focus:ring-rb-100'
const labelClass='mb-2 block text-sm font-black text-rb-900'

const configs={
  volunteer:{title:'Volunteer With Us',eyebrow:'Give your time',description:'Bring your skills, time and energy into verified RB Charity Foundation initiatives.',endpoint:'/api/volunteers',success:'Thank you. Your volunteer registration has been received.',icon:Users,image:charityMedia.editorial[0],points:['Contribute skills that match real initiative needs','Choose availability that works for you','Join a reviewed volunteer pipeline rather than a generic mailing list']},
  partner:{title:'Partner With Us',eyebrow:'Build impact together',description:'Collaborate as a company, institution, NGO or community organisation on work that can scale responsibly.',endpoint:'/api/partners',success:'Thank you. Your partnership enquiry has been received.',icon:Building2,image:charityMedia.editorial[3],points:['Corporate and institutional partnerships','NGO and community collaboration','Structured follow-up through the Admin partnership pipeline']},
  contact:{title:'Contact Us',eyebrow:'Start a conversation',description:'Reach the foundation team about donations, campaigns, volunteering, partnerships or general enquiries.',endpoint:'/api/contact',success:'Thank you. Your message has been received.',icon:MessageCircle,image:charityMedia.heroAlt,points:['Route your enquiry by category','Optional mobile contact for follow-up','Messages are tracked through the Admin engagement pipeline']}
}

const organisationOptions=[{value:'corporate',label:'Corporate'},{value:'ngo',label:'NGO'},{value:'institution',label:'Institution'},{value:'community',label:'Community organisation'},{value:'other',label:'Other'}]
const availabilityOptions=[{value:'weekdays',label:'Weekdays'},{value:'weekends',label:'Weekends'},{value:'flexible',label:'Flexible'},{value:'events-only',label:'Events only'}]
const enquiryOptions=[{value:'general',label:'General'},{value:'donation',label:'Donation'},{value:'volunteer',label:'Volunteer'},{value:'partnership',label:'Partnership'},{value:'campaign',label:'Campaign'},{value:'other',label:'Other'}]

export default function EngagementFormPage({type}){
  const config=configs[type],Icon=config.icon
  const [form,setForm]=useState(type==='partner'?{organisation:'',contactName:'',email:'',phone:'',type:'corporate',message:''}:type==='contact'?{name:'',email:'',phone:'',category:'general',subject:'',message:''}:{name:'',email:'',phone:'',city:'',skills:'',availability:'',message:''})
  const [status,setStatus]=useState({loading:false,error:'',success:false})
  const set=(key,value)=>setForm(current=>({...current,[key]:value}))
  async function submit(event){event.preventDefault();setStatus({loading:true,error:'',success:false});const payload=type==='volunteer'?{...form,skills:form.skills.split(',').map(item=>item.trim()).filter(Boolean)}:form;try{const response=await fetch(config.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.message||'Unable to submit the form');setStatus({loading:false,error:'',success:true})}catch(error){setStatus({loading:false,error:error.message,success:false})}}

  if(status.success)return <main className="bg-[#f7fafc] py-20"><div className={`${shell} max-w-4xl`}><div className="overflow-hidden rounded-[2.5rem] bg-rb-900 text-white shadow-2xl"><div className="relative min-h-[260px]"><img src={config.image} alt="RB Charity Foundation community work" className="absolute inset-0 h-full w-full object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-rb-950 via-rb-900/75 to-rb-900/25"/><div className="relative p-8 sm:p-10"><div className="grid h-16 w-16 place-items-center rounded-full bg-gold text-rb-900"><CheckCircle2 size={34}/></div><h1 className="mt-6 text-3xl font-black tracking-[-.04em] sm:text-4xl">Received successfully</h1><p className="mt-3 max-w-xl leading-7 text-white/70">{config.success}</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={()=>setStatus({loading:false,error:'',success:false})} className="rounded-full bg-gold px-6 py-3 font-black text-rb-900">Submit another response</button><Link to="/" className="rounded-full border border-white/15 bg-white/10 px-6 py-3 font-black text-white">Back home</Link></div></div></div></div></div></main>

  return <main className="bg-[#f7fafc]"><section className="relative isolate overflow-hidden bg-rb-950 text-white"><img src={config.image} alt="RB Charity Foundation community participation" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-rb-950 via-rb-950/88 to-rb-900/28"/><div className={`${shell} relative grid min-h-[520px] items-end gap-10 py-16 lg:grid-cols-[1fr_.52fr]`}><div><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-gold backdrop-blur"><Icon size={15}/>{config.eyebrow}</div><h1 className="mt-5 text-4xl font-black tracking-[-.05em] sm:text-6xl lg:text-7xl">{config.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/72">{config.description}</p></div><div className="rounded-[2rem] border border-white/15 bg-white/10 p-6 backdrop-blur-xl"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">What happens next</p><div className="mt-5 space-y-4">{config.points.map(item=><div key={item} className="flex items-start gap-3 text-sm font-semibold leading-6 text-white/75"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-gold"/>{item}</div>)}</div></div></div></section><section className="py-16 sm:py-24"><div className={shell}><div className="grid gap-8 xl:grid-cols-[.42fr_1fr]"><aside className="h-fit rounded-[2rem] bg-[#fff0d8] p-6 sm:p-7 xl:sticky xl:top-32"><Sparkles className="text-gold"/><p className="mt-4 text-xs font-black uppercase tracking-[.16em] text-rb-600">Participation with purpose</p><h2 className="mt-3 text-2xl font-black tracking-[-.03em] text-rb-900">A clear path from interest to action.</h2><p className="mt-4 leading-7 text-slate-600">Submissions are stored as real operational records, so the foundation team can review and follow up rather than lose enquiries in email.</p><Link to="/impact" className="mt-6 inline-flex items-center gap-2 font-black text-rb-800">See our impact model <ArrowRight size={16}/></Link></aside><form onSubmit={submit} className="grid gap-5 rounded-[2.4rem] border border-rb-100 bg-white p-6 shadow-xl shadow-rb-100/50 sm:p-8 md:grid-cols-2">
    {type==='partner'?<><Field label="Organisation"><input className={input} value={form.organisation} onChange={e=>set('organisation',e.target.value)} placeholder="Organisation name" required/></Field><Field label="Contact person"><input className={input} value={form.contactName} onChange={e=>set('contactName',e.target.value)} placeholder="Full name" required/></Field><Field label="Email"><input type="email" className={input} value={form.email} onChange={e=>set('email',e.target.value)} placeholder="you@example.com" required/></Field><Field label="Mobile number"><input inputMode="numeric" maxLength={10} className={input} value={form.phone} onChange={e=>set('phone',e.target.value.replace(/\D/g,''))} placeholder="10-digit mobile number" required/></Field><Field label="Organisation type"><CustomSelect value={form.type} onChange={value=>set('type',value)} options={organisationOptions}/></Field><div/><Field label="How would you like to collaborate?" full><textarea rows={5} className={`${input} resize-none`} value={form.message} onChange={e=>set('message',e.target.value)} placeholder="Tell us about the collaboration you have in mind" required/></Field></>:
    type==='contact'?<><Field label="Name"><input className={input} value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Your full name" required/></Field><Field label="Email"><input type="email" className={input} value={form.email} onChange={e=>set('email',e.target.value)} placeholder="you@example.com" required/></Field><Field label="Mobile number (optional)"><input inputMode="numeric" maxLength={10} className={input} value={form.phone} onChange={e=>set('phone',e.target.value.replace(/\D/g,''))} placeholder="10-digit mobile number"/></Field><Field label="Enquiry category"><CustomSelect value={form.category} onChange={value=>set('category',value)} options={enquiryOptions}/></Field><Field label="Subject" full><input className={input} value={form.subject} onChange={e=>set('subject',e.target.value)} placeholder="What is this about?"/></Field><Field label="Message" full><textarea rows={5} className={`${input} resize-none`} value={form.message} onChange={e=>set('message',e.target.value)} placeholder="Write your message" required/></Field></>:
    <><Field label="Name"><input className={input} value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Your full name" required/></Field><Field label="Email"><input type="email" className={input} value={form.email} onChange={e=>set('email',e.target.value)} placeholder="you@example.com" required/></Field><Field label="Mobile number"><input inputMode="numeric" maxLength={10} className={input} value={form.phone} onChange={e=>set('phone',e.target.value.replace(/\D/g,''))} placeholder="10-digit mobile number" required/></Field><Field label="City"><input className={input} value={form.city} onChange={e=>set('city',e.target.value)} placeholder="Your city"/></Field><Field label="Skills (comma separated)"><input className={input} value={form.skills} onChange={e=>set('skills',e.target.value)} placeholder="Teaching, design, logistics"/></Field><Field label="Availability"><CustomSelect value={form.availability} onChange={value=>set('availability',value)} options={availabilityOptions} placeholder="Select availability"/></Field><Field label="Why would you like to volunteer?" full><textarea rows={5} className={`${input} resize-none`} value={form.message} onChange={e=>set('message',e.target.value)} placeholder="Tell us how you would like to help"/></Field></>}
    {status.error&&<div className="md:col-span-2 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{status.error}</div>}
    <div className="md:col-span-2"><button disabled={status.loading} className="group inline-flex w-full items-center justify-center gap-2 rounded-full bg-gold px-6 py-3.5 font-black text-rb-900 shadow-lg shadow-orange-100 transition duration-300 hover:-translate-y-0.5 hover:shadow-xl disabled:cursor-not-allowed disabled:opacity-60 sm:w-auto">{status.loading?<Loader2 size={18} className="animate-spin"/>:<Send size={18} className="transition group-hover:translate-x-0.5"/>}{status.loading?'Submitting...':'Submit'}</button></div>
  </form></div></div></section></main>
}
function Field({label,children,full=false}){return <label className={full?'md:col-span-2':''}><span className={labelClass}>{label}</span>{children}</label>}
