import { AlertTriangle, ArrowLeft, Home, SearchX } from 'lucide-react'
import { Link } from 'react-router-dom'
import { LOGO_URL } from '../components/SiteLayout'

const shell='mx-auto w-full max-w-7xl px-5 sm:px-6 lg:px-8'

export function NotFoundPage(){return <main className="bg-[#f8fbff] text-rb-900"><section className="relative overflow-hidden bg-rb-900 py-20 text-white sm:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(242,162,58,.2),transparent_30%),radial-gradient(circle_at_10%_80%,rgba(55,105,166,.5),transparent_38%)]"/><div className={`${shell} relative text-center`}><img src={LOGO_URL} alt="RB Charity Foundation" className="mx-auto h-24 w-24 object-contain"/><div className="mx-auto mt-6 grid h-14 w-14 place-items-center rounded-full bg-white/10 text-gold"><SearchX size={26}/></div><p className="mt-6 text-sm font-black uppercase tracking-[.24em] text-gold">404 · Page not found</p><h1 className="mx-auto mt-4 max-w-3xl text-4xl font-black tracking-[-.04em] sm:text-6xl">This page seems to have moved beyond our map.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white/65">The link may be outdated, incomplete, or the page may no longer exist.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link to="/" className="inline-flex items-center gap-2 rounded-full bg-gold px-6 py-3.5 font-black text-rb-900"><Home size={17}/>Back home</Link><Link to="/contact" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-6 py-3.5 font-black text-white"><ArrowLeft size={17}/>Contact us</Link></div></div></section></main>}

export function ErrorPage(){return <main className="grid min-h-[70vh] place-items-center bg-[#f8fbff] px-5 py-16 text-rb-900"><div className="w-full max-w-xl rounded-[2rem] border border-rb-100 bg-white p-8 text-center shadow-xl"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-red-50 text-red-600"><AlertTriangle size={25}/></div><h1 className="mt-5 text-3xl font-black">We couldn’t load this page</h1><p className="mt-3 leading-7 text-slate-600">An unexpected page-level problem occurred. You can retry or return to the foundation homepage.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><button type="button" onClick={()=>window.location.reload()} className="rounded-full bg-rb-900 px-5 py-3 font-black text-white">Try again</button><Link to="/" className="rounded-full border border-rb-100 px-5 py-3 font-black text-rb-900">Go home</Link></div></div></main>}
