import { AlertTriangle, ArrowLeft, ArrowRight, Home, RefreshCw, SearchX } from 'lucide-react'
import { Link } from 'react-router-dom'
import { LOGO_URL } from '../components/SiteLayout'
import { charityMedia } from '../data/charityMedia'

const shell='mx-auto w-full max-w-7xl px-5 sm:px-6 lg:px-8'

export function NotFoundPage(){return <main className="bg-[#f7fafc] text-rb-900"><section className="relative isolate overflow-hidden bg-rb-950 text-white"><img src={charityMedia.editorial[1]} alt="RB Charity Foundation community work" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-rb-950 via-rb-950/92 to-rb-900/35"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(242,162,58,.22),transparent_30%)]"/><div className={`${shell} relative grid min-h-[640px] items-center gap-10 py-16 lg:grid-cols-[1fr_.5fr]`}><div><img src={LOGO_URL} alt="RB Charity Foundation" width="96" height="96" className="h-24 w-24 object-contain"/><p className="mt-8 text-sm font-black uppercase tracking-[.24em] text-gold">404 · Page not found</p><h1 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.055em] sm:text-6xl lg:text-7xl">This page has moved beyond our map.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">The link may be outdated, incomplete or the page may no longer exist. The rest of the foundation site is still available.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/" className="inline-flex items-center gap-2 rounded-full bg-gold px-6 py-3.5 font-black text-rb-900"><Home size={17}/>Back home</Link><Link to="/campaigns" className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-6 py-3.5 font-black text-white">Explore campaigns <ArrowRight size={17}/></Link></div></div><div className="rounded-[2rem] border border-white/15 bg-white/10 p-7 backdrop-blur-xl"><div className="grid h-14 w-14 place-items-center rounded-full bg-white/10 text-gold"><SearchX size={26}/></div><h2 className="mt-5 text-2xl font-black">Looking for something specific?</h2><p className="mt-3 leading-7 text-white/65">Try the main navigation, visit the Contact page or return to current campaigns and causes.</p><Link to="/contact" className="mt-6 inline-flex items-center gap-2 font-black text-gold">Contact us <ArrowRight size={16}/></Link></div></div></section></main>}

export function ErrorPage(){return <main className="bg-[#f7fafc] text-rb-900"><section className="relative isolate overflow-hidden bg-rb-950 text-white"><img src={charityMedia.editorial[2]} alt="RB Charity Foundation field activity" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-rb-950 via-rb-950/92 to-rb-900/40"/><div className={`${shell} relative grid min-h-[620px] place-items-center py-16`}><div className="w-full max-w-3xl rounded-[2.5rem] border border-white/15 bg-white/10 p-8 text-center backdrop-blur-xl sm:p-10"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-red-500/15 text-red-200"><AlertTriangle size={28}/></div><p className="mt-6 text-xs font-black uppercase tracking-[.2em] text-gold">Something went wrong</p><h1 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-5xl">We couldn’t load this page.</h1><p className="mx-auto mt-4 max-w-xl leading-7 text-white/65">An unexpected page-level problem occurred. Retry the page, return home, or contact the foundation if the issue continues.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><button type="button" onClick={()=>window.location.reload()} className="inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 font-black text-rb-900"><RefreshCw size={16}/>Try again</button><Link to="/" className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-5 py-3 font-black text-white"><ArrowLeft size={16}/>Go home</Link></div></div></div></section></main>}
