import { ArrowUp, Heart, Mail, MapPin, Menu, Phone, X } from 'lucide-react'
import { FaFacebookF, FaInstagram, FaYoutube } from 'react-icons/fa'
import { useEffect, useState } from 'react'
import { Link, NavLink, useLocation } from 'react-router-dom'

export const LOGO_URL = 'https://media.githubusercontent.com/media/Shahzadkhanks19/rbserviceconnect/main/images/Charity-Logo-sample-1%20(1).png'
export const LEGACY_IMAGE_BASE = 'https://media.githubusercontent.com/media/Shahzadkhanks19/rbserviceconnect/main/images/'
const nav = [['Home','/'],['About','/about'],['Causes','/causes'],['Campaigns','/campaigns'],['Impact','/impact'],['Stories','/stories'],['Volunteer','/volunteer'],['Contact','/contact']]
const shell = 'mx-auto w-full max-w-7xl px-5 sm:px-6 lg:px-8'
const focusRing = 'focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-gold/35'

function usePublicSettings(){
  const [settings,setSettings]=useState({})
  useEffect(()=>{let active=true;fetch('/api/public/settings').then(async response=>{const text=await response.text();const data=text?JSON.parse(text):{};if(active&&response.ok&&data.success)setSettings(data.settings||{})}).catch(()=>{});return()=>{active=false}},[])
  return settings
}
function ScrollToTopOnRoute(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo({top:0,left:0,behavior:'instant'})},[pathname]);return null}

export function SiteHeader(){
  const [open,setOpen]=useState(false)
  const {pathname}=useLocation()
  useEffect(()=>setOpen(false),[pathname])
  useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>{document.body.style.overflow=''}},[open])
  useEffect(()=>{if(!open)return undefined;const close=event=>{if(event.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open])
  const linkClass=({isActive})=>`rounded-full px-3 py-2 text-sm font-semibold transition duration-300 hover:-translate-y-0.5 hover:bg-rb-50 hover:text-rb-900 hover:shadow-sm ${focusRing} ${isActive?'bg-rb-50 text-rb-900':'text-rb-900/70'}`
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/80 bg-[#fffaf2]/95 shadow-sm backdrop-blur-xl"><div className={`${shell} flex h-24 items-center justify-between gap-4`}><Link to="/" aria-label="RB Charity Foundation home" className={`shrink-0 rounded-xl ${focusRing}`}><img src={LOGO_URL} alt="RB Charity Foundation" width="120" height="72" fetchPriority="high" decoding="async" className="h-16 w-[105px] object-contain sm:h-[72px] sm:w-[120px]"/></Link><nav aria-label="Primary navigation" className="hidden items-center gap-1 xl:flex">{nav.map(([label,path])=><NavLink key={path} to={path} className={linkClass}>{label}</NavLink>)}</nav><Link to="/donate" className={`hidden items-center gap-2 rounded-full bg-gold px-5 py-3 text-sm font-black text-rb-900 shadow-sm transition hover:-translate-y-1 hover:shadow-lg lg:inline-flex ${focusRing}`}>Donate now <Heart size={16}/></Link><button type="button" onClick={()=>setOpen(v=>!v)} className={`grid h-11 w-11 place-items-center rounded-xl text-rb-900 transition hover:bg-rb-50 xl:hidden ${focusRing}`} aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="mobile-navigation">{open?<X aria-hidden="true"/>:<Menu aria-hidden="true"/>}</button></div>{open&&<div id="mobile-navigation" className="max-h-[calc(100vh-6rem)] overflow-y-auto border-t border-slate-200 bg-[#fffaf2] px-5 py-5 shadow-xl xl:hidden"><nav aria-label="Mobile navigation" className="mx-auto max-w-7xl">{nav.map(([label,path])=><NavLink key={path} to={path} className={({isActive})=>`block rounded-xl px-3 py-3 font-semibold transition ${focusRing} ${isActive?'bg-rb-50 text-rb-900':'text-rb-900/75 hover:bg-rb-50 hover:text-rb-900'}`}>{label}</NavLink>)}<Link to="/donate" className={`mt-4 inline-flex w-full items-center justify-center gap-2 rounded-full bg-gold px-5 py-3 font-black text-rb-900 ${focusRing}`}>Donate now <Heart size={16}/></Link></nav></div>}</header>
}

export function SiteFooter(){
  const settings=usePublicSettings()
  const footerLink=`rounded-lg px-2 py-1.5 -ml-2 text-rb-900/65 transition duration-300 hover:translate-x-1 hover:bg-rb-50 hover:text-rb-900 ${focusRing}`
  const Group=({title,links})=><div><h2 className="text-xs font-black uppercase tracking-[.18em] text-rb-900/55">{title}</h2><nav aria-label={`${title} footer links`} className="mt-5 flex flex-col items-start gap-1">{links.map(([label,path])=><Link key={path} className={footerLink} to={path}>{label}</Link>)}</nav></div>
  const socialClass=`grid h-11 w-11 place-items-center rounded-full border border-rb-100 bg-white text-rb-700 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-gold/50 hover:bg-gold hover:text-rb-900 hover:shadow-md ${focusRing}`
  const socialDisabledClass='grid h-11 w-11 place-items-center rounded-full border border-rb-100 bg-white text-rb-700/35 shadow-sm'
  const socials=[[settings['social.instagram'],<FaInstagram size={18}/>,'Instagram'],[settings['social.facebook'],<FaFacebookF size={17}/>,'Facebook'],[settings['social.youtube'],<FaYoutube size={19}/>,'YouTube']]
  const description=settings['footer.description']||'Business-backed social impact with a transparent pathway for public participation.'
  const contact=[[settings['contact.email'],Mail],[settings['contact.phone'],Phone],[settings['contact.address'],MapPin]].filter(([value])=>value)
  return <footer className="border-t border-rb-100 bg-[#fffaf2] text-rb-900"><div className={`${shell} grid gap-10 py-14 sm:grid-cols-2 sm:py-16 xl:grid-cols-[1.25fr_.8fr_.8fr_.8fr_.8fr]`}><div><Link to="/" aria-label="RB Charity Foundation home" className={`inline-flex rounded-xl ${focusRing}`}><img src={LOGO_URL} alt="RB Charity Foundation" width="175" height="112" loading="lazy" decoding="async" className="h-24 w-[150px] object-contain object-left sm:h-28 sm:w-[175px]"/></Link><p className="mt-4 text-lg font-black">RB CHARITY FOUNDATION</p><p className="mt-4 max-w-md leading-7 text-rb-900/60">{description}</p>{contact.length>0&&<address className="mt-5 space-y-2 not-italic">{contact.map(([value,Icon])=><div key={value} className="flex min-w-0 items-start gap-2 text-sm text-rb-900/60"><Icon size={15} className="mt-0.5 shrink-0" aria-hidden="true"/><span className="break-words">{value}</span></div>)}</address>}<div className="mt-6 flex items-center gap-3" aria-label="Social links">{socials.map(([url,icon,label])=>url?<a key={label} href={url} target="_blank" rel="noopener noreferrer" aria-label={`${label} — opens in a new tab`} className={socialClass}>{icon}</a>:<span key={label} aria-hidden="true" title={`${label} link not configured`} className={socialDisabledClass}>{icon}</span>)}</div></div><Group title="Foundation" links={[["Home","/"],["About","/about"],["Impact","/impact"],["Transparency","/transparency"]]}/><Group title="Our work" links={[["Causes","/causes"],["Campaigns","/campaigns"],["Stories","/stories"],["Gallery","/gallery"]]}/><Group title="Get involved" links={[["Donate","/donate"],["Volunteer","/volunteer"],["Partner","/partner"],["Contact","/contact"]]}/><Group title="Resources" links={[["Reports","/reports"],["FAQ","/faq"],["Privacy","/privacy"],["Terms","/terms"],["Refund policy","/refund-policy"]]}/></div><div className="border-t border-rb-100"><div className={`${shell} py-7 pr-20 text-center text-sm leading-6 text-rb-900/50 sm:pr-24`}><span>© {new Date().getFullYear()} RB Charity Foundation. All rights reserved.</span></div></div></footer>
}

export function FloatingActions(){const [showTop,setShowTop]=useState(false);useEffect(()=>{const onScroll=()=>setShowTop(window.scrollY>240);onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);return <div className="fixed bottom-4 right-3 z-40 flex flex-col items-center gap-2 sm:bottom-7 sm:right-7 sm:gap-3">{showTop&&<button type="button" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="Scroll to top" className={`grid h-11 w-11 place-items-center rounded-full bg-rb-900 text-white shadow-xl transition duration-300 hover:-translate-y-1 hover:bg-rb-800 sm:h-12 sm:w-12 ${focusRing}`}><ArrowUp size={20}/></button>}<Link to="/donate" aria-label="Donate now" className={`group flex flex-col items-center gap-1.5 rounded-full ${focusRing}`}><span className="grid h-11 w-11 place-items-center rounded-full bg-gold shadow-xl ring-2 ring-white/80 transition duration-300 group-hover:-translate-y-1 group-hover:scale-105 group-hover:shadow-2xl sm:h-12 sm:w-12"><Heart size={20} fill="currentColor" className="transition duration-300 group-hover:scale-110"/></span><span className="hidden rounded-full bg-white/95 px-2 py-0.5 text-[10px] font-black shadow-md backdrop-blur sm:block sm:text-[11px]">Donate now</span></Link></div>}
export default function SiteLayout({children}){return <><ScrollToTopOnRoute/><a href="#main-content" className="fixed left-3 top-3 z-[100] -translate-y-24 rounded-full bg-gold px-4 py-2 font-black text-rb-950 shadow-xl transition focus:translate-y-0">Skip to content</a><SiteHeader/><div id="main-content" tabIndex="-1" className="pt-24 outline-none">{children}</div><SiteFooter/><FloatingActions/></>}
