import { ArrowRight, BookOpen, CheckCircle2, HandHeart, Heart, ShieldCheck, Users, Sparkles, TrendingUp } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { FloatingActions, SiteFooter, SiteHeader } from './components/SiteLayout'
import { charityFallback, charityMedia } from './data/charityMedia'

const shell='mx-auto w-full max-w-7xl px-5 sm:px-6 lg:px-8'
const focusRing='focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-gold/35'
const formatMoney=value=>`₹${Number(value||0).toLocaleString('en-IN')}`

function App(){
  const [causeState,setCauseState]=useState({loading:true,items:[],error:false})
  const [campaignState,setCampaignState]=useState({loading:true,items:[],error:false})
  const [storyState,setStoryState]=useState({loading:true,items:[],error:false})
  const [impactState,setImpactState]=useState({loading:true,summary:null})
  useEffect(()=>{let active=true;Promise.allSettled([
    fetch('/api/causes').then(async response=>{const data=await response.json();if(!response.ok||!data.success)throw new Error();return (data.data||[]).slice(0,6)}),
    fetch('/api/campaigns').then(async response=>{const data=await response.json();if(!response.ok||!data.success)throw new Error();return (data.data||[]).filter(item=>item.status==='active').slice(0,4)}),
    fetch('/api/public/stories').then(async response=>{const data=await response.json();if(!response.ok||!data.success)throw new Error();return (data.items||[]).slice(0,4)}),
    fetch('/api/public/impact-summary').then(async response=>{const data=await response.json();if(!response.ok||!data.success)throw new Error();return data.summary||null})
  ]).then(([causes,campaigns,stories,impact])=>{if(!active)return;setCauseState(causes.status==='fulfilled'?{loading:false,items:causes.value,error:false}:{loading:false,items:[],error:true});setCampaignState(campaigns.status==='fulfilled'?{loading:false,items:campaigns.value,error:false}:{loading:false,items:[],error:true});setStoryState(stories.status==='fulfilled'?{loading:false,items:stories.value,error:false}:{loading:false,items:[],error:true});setImpactState({loading:false,summary:impact.status==='fulfilled'?impact.value:null})});return()=>{active=false}},[])
  const impactMetrics=impactState.summary?[["Verified funds raised",formatMoney(impactState.summary.totalRaised)],["Supporters recorded",Number(impactState.summary.donors||0).toLocaleString('en-IN')],["Active/completed campaigns",Number(impactState.summary.campaigns||0).toLocaleString('en-IN')],["Approved volunteers",Number(impactState.summary.volunteers||0).toLocaleString('en-IN')]]:[]
  const featuredCampaign=campaignState.items[0]
  const campaignProgress=featuredCampaign?.goalAmount?Math.min(100,Math.round((Number(featuredCampaign.raisedAmount||0)/Number(featuredCampaign.goalAmount))*100)):0

  return <main className="overflow-hidden bg-[#f7fafc] text-slate-900"><SiteHeader/>
    <section className="relative isolate bg-rb-950 pt-24 text-white"><img src={charityMedia.hero} alt="RB Charity Foundation community initiative" className="absolute inset-0 h-full w-full object-cover" fetchPriority="high"/><div className="absolute inset-0 bg-gradient-to-r from-rb-950 via-rb-950/86 to-rb-900/25"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_18%,rgba(242,162,58,.22),transparent_28%)]"/><div className={`${shell} relative grid min-h-[calc(100svh-6rem)] items-end gap-10 py-14 lg:grid-cols-[1fr_.52fr] lg:py-16`}><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-[.2em] text-gold backdrop-blur"><Sparkles size={14}/>Profits with purpose</div><h1 className="mt-6 text-4xl font-black leading-[.96] tracking-[-.06em] sm:text-6xl lg:text-7xl xl:text-8xl">Turning business success into <span className="text-gold">human impact.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/72">RB Charity Foundation channels business-backed support and public participation into verified causes, campaigns and community work.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><Link to="/donate" className={`inline-flex items-center justify-center gap-2 rounded-full bg-gold px-6 py-3.5 font-black text-rb-900 transition hover:-translate-y-1 ${focusRing}`}>Make a difference <ArrowRight size={18}/></Link><Link to="/campaigns" className={`inline-flex items-center justify-center rounded-full border border-white/20 bg-white/10 px-6 py-3.5 font-black text-white backdrop-blur transition hover:-translate-y-1 hover:bg-white/15 ${focusRing}`}>Explore live campaigns</Link></div></div><div className="rounded-[2rem] border border-white/15 bg-white/10 p-6 backdrop-blur-xl"><ShieldCheck className="text-gold"/><p className="mt-4 text-xs font-black uppercase tracking-[.18em] text-gold">A transparent participation model</p><div className="mt-5 space-y-4">{['Verified payments update the donation ledger','Campaign totals reconcile from successful donations','Stories, gallery media and reports document field progress'].map(item=><div key={item} className="flex items-start gap-3 text-sm font-semibold leading-6 text-white/75"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-gold"/>{item}</div>)}</div></div></div></section>

    <section className="py-16 sm:py-24"><div className={`${shell} grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center`}><div><p className="text-xs font-black uppercase tracking-[.18em] text-rb-600">Our foundation</p><h2 className="mt-3 text-3xl font-black tracking-[-.045em] text-rb-900 sm:text-5xl">A social-impact arm built around responsibility, dignity and action.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The foundation connects commercial growth with social responsibility while giving individuals, volunteers and institutions clear ways to participate.</p><Link to="/about" className={`mt-7 inline-flex items-center gap-2 rounded-full bg-rb-900 px-5 py-3 font-black text-white ${focusRing}`}>Learn about the model <ArrowRight size={16}/></Link></div><div className="relative grid grid-cols-2 gap-4"><img src={charityMedia.editorial[0]} alt="Community field work" loading="lazy" decoding="async" className="aspect-[4/5] w-full rounded-[2rem] object-cover"/><img src={charityMedia.editorial[1]} alt="Foundation initiative" loading="lazy" decoding="async" className="mt-10 aspect-[4/5] w-full rounded-[2rem] object-cover"/><div className="absolute bottom-5 left-1/2 w-[74%] -translate-x-1/2 rounded-[1.5rem] bg-rb-900 p-5 text-white shadow-2xl"><p className="text-xs font-black uppercase tracking-[.16em] text-gold">Long-term thinking</p><p className="mt-2 font-black leading-6">Support should create repeatable systems, not just one-day visibility.</p></div></div></div></section>

    <section className="bg-rb-900 py-16 text-white sm:py-24"><div className={shell}><div className="mb-10 grid gap-4 lg:grid-cols-[1fr_.5fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-gold">Our causes</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-5xl">Focused areas where support can create lasting change.</h2></div><p className="leading-7 text-white/65">Published cause areas come directly from Admin and can grow as the foundation verifies new priorities.</p></div>{causeState.loading?<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="h-80 animate-pulse rounded-[2rem] bg-white/10"/>)}</div>:causeState.items.length?<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{causeState.items.map((cause,i)=><Link to={`/causes/${cause.slug}`} key={cause._id||cause.slug} className={`group relative min-h-[350px] overflow-hidden rounded-[2rem] ${focusRing}`}><img src={cause.image||charityFallback('causes',i)} alt={cause.name} loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-rb-950/95 via-rb-900/25 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6"><span className="text-xs font-black uppercase tracking-[.16em] text-gold">Cause {String(i+1).padStart(2,'0')}</span><h3 className="mt-3 text-2xl font-black">{cause.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-white/65">{cause.summary||cause.description}</p><span className="mt-5 inline-flex items-center gap-2 font-black text-white">Explore cause <ArrowRight size={16}/></span></div></Link>)}</div>:<EmptyState title={causeState.error?'Unable to load causes':'No published causes yet'}/>}<Link to="/causes" className="mt-8 inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 font-black text-rb-900">View all causes <ArrowRight size={16}/></Link></div></section>

    <section className="py-16 sm:py-24"><div className={shell}><div className="mb-10 grid gap-4 lg:grid-cols-[1fr_.5fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-rb-600">Featured campaign</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] text-rb-900 sm:text-5xl">See where support is active right now.</h2></div><p className="leading-7 text-slate-600">Funding progress is calculated from verified successful donations rather than manually entered totals.</p></div>{campaignState.loading?<div className="h-[480px] animate-pulse rounded-[2.5rem] bg-white"/>:featuredCampaign?<article className="grid overflow-hidden rounded-[2.5rem] bg-white shadow-2xl shadow-rb-100/60 lg:grid-cols-[1.1fr_.9fr]"><div className="relative min-h-[380px]"><img src={featuredCampaign.coverImage||charityFallback('campaigns',0)} alt={featuredCampaign.title} loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-rb-950/55 to-transparent"/></div><div className="flex flex-col justify-center p-7 sm:p-10"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-rb-50 px-3 py-1 text-xs font-black uppercase tracking-[.14em] text-rb-700">{featuredCampaign.cause?.name||'Foundation campaign'}</span><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black uppercase tracking-[.14em] text-emerald-700">Active</span></div><h3 className="mt-5 text-3xl font-black tracking-[-.04em] text-rb-900 sm:text-4xl">{featuredCampaign.title}</h3><p className="mt-4 line-clamp-4 leading-7 text-slate-600">{featuredCampaign.summary||featuredCampaign.description}</p><div className="mt-7"><div className="flex justify-between gap-4 text-sm font-black text-slate-600"><span>{formatMoney(featuredCampaign.raisedAmount)} raised</span><span>{formatMoney(featuredCampaign.goalAmount)} goal</span></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-rb-50"><div className="h-full rounded-full bg-gold" style={{width:`${campaignProgress}%`}}/></div><p className="mt-2 text-xs font-bold text-slate-400">{campaignProgress}% funded</p></div><div className="mt-7 flex flex-wrap gap-3"><Link to={`/campaigns/${featuredCampaign.slug}`} className="inline-flex items-center gap-2 rounded-full bg-rb-900 px-5 py-3 font-black text-white">View campaign <ArrowRight size={16}/></Link><Link to={`/donate?campaign=${encodeURIComponent(featuredCampaign.slug)}`} className="rounded-full bg-gold px-5 py-3 font-black text-rb-900">Donate now</Link></div></div></article>:<EmptyState title={campaignState.error?'Unable to load campaigns':'No active campaigns yet'}/>}</div></section>

    <section className="bg-[#fff0d8] py-16 sm:py-24"><div className={shell}><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-rb-600">Verified impact</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] text-rb-900 sm:text-5xl">Numbers that come from operational records.</h2><p className="mt-5 leading-7 text-slate-600">The public impact summary uses the same donation, donor, campaign and volunteer records that power Admin.</p><Link to="/impact" className="mt-7 inline-flex items-center gap-2 font-black text-rb-800">Explore impact <ArrowRight size={16}/></Link></div>{impactState.loading?<div className="grid gap-4 sm:grid-cols-2">{Array.from({length:4}).map((_,i)=><div key={i} className="h-36 animate-pulse rounded-[2rem] bg-white"/>)}</div>:impactMetrics.length?<div className="grid gap-4 sm:grid-cols-2">{impactMetrics.map(([title,value],i)=><div key={title} className={`rounded-[2rem] p-6 ${i===0?'bg-rb-900 text-white':'bg-white text-rb-900 shadow-sm'}`}><TrendingUp className={i===0?'text-gold':'text-rb-600'}/><p className={`mt-4 break-words text-3xl font-black ${i===0?'text-gold':''}`}>{value}</p><h3 className={`mt-2 text-sm font-bold ${i===0?'text-white/60':'text-slate-500'}`}>{title}</h3></div>)}</div>:<EmptyState title="Verified impact totals are not available right now."/>}</div></div></section>

    <section className="py-16 sm:py-24"><div className={shell}><div className="mb-10 grid gap-4 lg:grid-cols-[1fr_.5fr] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-rb-600">Stories of change</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] text-rb-900 sm:text-5xl">The people behind the work matter more than the numbers.</h2></div><p className="leading-7 text-slate-600">Stories published through the CMS add context to campaigns and field evidence.</p></div>{storyState.loading?<div className="grid gap-5 lg:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i} className="h-96 animate-pulse rounded-[2rem] bg-white"/>)}</div>:storyState.items.length?<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{storyState.items.map((story,i)=><Link key={story._id||story.slug} to={`/stories/${story.slug}`} className={`group overflow-hidden rounded-[2rem] border border-rb-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl ${focusRing}`}><div className="relative aspect-[4/3] overflow-hidden"><img src={story.coverImage||charityFallback('editorial',i)} alt={story.title} loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-rb-950/50 to-transparent"/></div><div className="p-5"><p className="text-xs font-black uppercase tracking-[.14em] text-rb-600">{story.category||'Foundation update'}</p><h3 className="mt-3 text-xl font-black text-rb-900">{story.title}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-600">{story.excerpt}</p><span className="mt-4 inline-flex items-center gap-2 font-black text-rb-700">Read story <ArrowRight size={16}/></span></div></Link>)}</div>:<EmptyState title={storyState.error?'Unable to load stories':'No published stories yet'}/>}<Link to="/stories" className="mt-8 inline-flex items-center gap-2 rounded-full bg-rb-900 px-5 py-3 font-black text-white">View all stories <ArrowRight size={16}/></Link></div></section>

    <section className="pb-20 sm:pb-24"><div className={shell}><div className="grid overflow-hidden rounded-[2.5rem] bg-rb-900 text-white lg:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-[360px]"><img src={charityMedia.editorial[3]} alt="Community participation" loading="lazy" decoding="async" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-rb-950/65 to-transparent"/></div><div className="p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-gold">Get involved</p><h2 className="mt-3 text-3xl font-black tracking-[-.04em] sm:text-4xl">There is more than one way to contribute.</h2><div className="mt-7 grid gap-3">{[[HandHeart,'Volunteer','Give your time and skills to initiatives.','/volunteer'],[Users,'Partner','Collaborate as a company, institution or NGO.','/partner'],[Heart,'Donate','Support the foundation or a specific campaign.','/donate']].map(([Icon,title,copy,path])=><Link to={path} key={title} className="group flex items-center gap-4 rounded-[1.5rem] border border-white/10 bg-white/8 p-4 transition hover:bg-white/12"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-gold text-rb-900"><Icon size={20}/></span><div><h3 className="font-black">{title}</h3><p className="mt-1 text-sm text-white/55">{copy}</p></div><ArrowRight size={17} className="ml-auto transition group-hover:translate-x-1"/></Link>)}</div></div></div></div></section>

    <SiteFooter/><FloatingActions/>
  </main>
}
function EmptyState({title}){return <div className="rounded-[2rem] border border-dashed border-rb-200 bg-white p-8 text-center"><BookOpen className="mx-auto text-rb-500"/><h3 className="mt-4 text-xl font-black text-rb-900">{title}</h3></div>}
export default App
