import { ArrowRight, CheckCircle2, Heart, HandHeart, Menu, ShieldCheck, Users, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useState } from 'react'
import { FloatingActions, SiteFooter } from './components/SiteLayout'
import usePublicContent, { cmsValue } from './hooks/usePublicContent'

const LOGO_URL = 'https://media.githubusercontent.com/media/Shahzadkhanks19/rbserviceconnect/main/images/Charity-Logo-sample-1%20(1).png'
const causes = [['Hunger & Food Support','Nutritious meals and essential food support for vulnerable communities.'],['Education','Learning support, school resources and opportunities for children and young people.'],['Healthcare','Medical assistance and healthcare support for people who need it most.'],['Women Empowerment','Helping women access skills, opportunities and pathways to greater independence.'],['Emergency Relief','Rapid support for families and communities during urgent situations.'],['Community Development','Long-term initiatives focused on dignity, opportunity and stronger communities.']]
const nav = [['Home','/'],['About','/about'],['Causes','/causes'],['Campaigns','/campaigns'],['Impact','/impact'],['Stories','/stories'],['Volunteer','/volunteer'],['Contact','/contact']]
const shell='mx-auto w-full max-w-7xl px-5 sm:px-6 lg:px-8'
const eyebrow='inline-flex items-center gap-2 rounded-full border border-rb-100 bg-rb-50 px-3 py-1 text-xs font-bold uppercase tracking-[0.18em] text-rb-700 transition duration-300 hover:-translate-y-0.5 hover:border-gold/50 hover:bg-white hover:shadow-sm'
const sectionTitle='mt-4 max-w-3xl text-3xl font-black tracking-[-0.04em] text-rb-900 sm:text-4xl lg:text-5xl'
const sectionCopy='mt-4 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg'
const navLink='group relative rounded-full px-3 py-2 text-sm font-semibold text-rb-900/70 transition duration-300 hover:-translate-y-0.5 hover:bg-rb-50 hover:text-rb-900 hover:shadow-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold/70'
function BrandLogo(){return <img src={LOGO_URL} alt="RB Charity Foundation" className="h-16 w-auto max-w-[105px] object-contain transition duration-500 hover:-rotate-1 hover:scale-105 sm:h-[72px] sm:max-w-[120px]"/>}

function App(){
 const [open,setOpen]=useState(false)
 const {content}=usePublicContent()
 const heroEyebrow=cmsValue(content,'home.hero.eyebrow','Profits with purpose')
 const heroTitle=cmsValue(content,'home.hero.title','Turning business success into human impact.')
 const heroCopy=cmsValue(content,'home.hero.copy','RB Charity Foundation channels support from the wider RB group and public donors into meaningful social initiatives across food, education, healthcare and community welfare.')
 const aboutTitle=cmsValue(content,'home.about.title','A charitable arm built around responsibility, dignity and action.')
 const aboutCopy=cmsValue(content,'home.about.copy','RB Charity Foundation exists to convert commercial growth into positive social outcomes. Alongside contributions connected to RB businesses, the platform gives individuals and partners a clear way to support causes they believe in.')
 const causesTitle=cmsValue(content,'home.causes.title','Focused areas where support can create lasting change.')
 const causesCopy=cmsValue(content,'home.causes.copy','These categories form the foundation of the platform. Real campaigns and verified impact figures will be published as they are approved.')
 const impactTitle=cmsValue(content,'home.impact.title','Every contribution should have a story you can follow.')
 const impactCopy=cmsValue(content,'home.impact.copy','The platform is designed around traceable campaigns, updates, reports and real impact data rather than decorative numbers.')
 const storiesTitle=cmsValue(content,'home.stories.title','The people behind every campaign matter more than the numbers.')
 return <main className="overflow-hidden bg-[#f8fbff] text-slate-900">
  <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/80 bg-[#fffaf2]/95 text-rb-900 shadow-sm backdrop-blur-xl"><div className={`${shell} flex h-24 items-center justify-between gap-6`}><Link to="/" className="flex shrink-0 items-center" aria-label="RB Charity Foundation home"><BrandLogo/></Link><nav className="hidden items-center gap-1 xl:flex">{nav.map(([item,path])=><Link key={path} to={path} className={navLink}>{item}</Link>)}</nav><div className="hidden lg:block"><Link to="/donate" className="group inline-flex items-center gap-2 rounded-full bg-gold px-5 py-3 text-sm font-black text-rb-900 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span>Donate now</span><Heart size={16}/></Link></div><button className="rounded-xl p-2 text-rb-900 xl:hidden" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></div>{open&&<div className="border-t border-slate-200 bg-[#fffaf2] px-5 py-5 shadow-xl xl:hidden">{nav.map(([item,path])=><Link onClick={()=>setOpen(false)} key={path} to={path} className="block rounded-xl px-3 py-3 font-semibold text-rb-900/75 hover:bg-rb-50">{item}</Link>)}<Link onClick={()=>setOpen(false)} to="/donate" className="mt-4 inline-flex w-full justify-center rounded-full bg-gold px-5 py-3 font-black">Donate now</Link></div>}</header>
  <section className="relative min-h-screen bg-rb-900 pt-24 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,rgba(242,162,58,.26),transparent_30%),radial-gradient(circle_at_10%_80%,rgba(55,105,166,.62),transparent_38%)]"/><div className={`${shell} relative grid min-h-[calc(100vh-6rem)] items-center gap-14 py-20 lg:grid-cols-[1.15fr_.85fr]`}><div><span className="inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.2em] text-white/80 backdrop-blur">{heroEyebrow}</span><h1 className="mt-6 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.055em] sm:text-6xl lg:text-7xl">{heroTitle}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">{heroCopy}</p><div className="mt-9 flex flex-wrap gap-4"><Link to="/donate" className="inline-flex items-center gap-2 rounded-full bg-gold px-6 py-3.5 font-black text-rb-900">Make a difference <ArrowRight size={18}/></Link><Link to="/causes" className="rounded-full border border-white/20 px-6 py-3.5 font-bold">Explore our work</Link></div></div><div className="relative mx-auto w-full max-w-lg"><div className="rounded-[2.2rem] border border-white/15 bg-white/10 p-5 shadow-2xl backdrop-blur-xl"><div className="rounded-[1.7rem] bg-white p-6 text-rb-900"><span className="text-xs font-black uppercase tracking-[.18em] text-rb-600">How RB creates impact</span><div className="mt-6 space-y-3">{['RB Group businesses grow','A share of success supports the foundation','Public donors can join the mission','Resources reach verified social initiatives'].map((item,index)=><div key={item} className="flex items-center gap-4 rounded-2xl bg-rb-50 p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-rb-800 text-sm font-black text-white">{index+1}</span><p className="font-bold">{item}</p></div>)}</div></div></div></div></div></section>
  <section className="py-24 sm:py-32"><div className={`${shell} grid gap-14 lg:grid-cols-2 lg:items-center`}><div><span className={eyebrow}>Our foundation</span><h2 className={sectionTitle}>{aboutTitle}</h2><p className={sectionCopy}>{aboutCopy}</p><Link to="/about" className="mt-6 inline-flex items-center gap-2 font-black text-rb-700">Learn about us <ArrowRight size={17}/></Link></div><div className="grid gap-4 sm:grid-cols-2">{[['Business-backed giving','A sustainable model that connects business performance with community responsibility.'],['Public participation','Supporters can contribute directly to the foundation or to specific campaigns.'],['Transparent impact','Campaign updates and reporting are designed to show where support goes.'],['Long-term thinking','We focus on meaningful, repeatable initiatives rather than one-time visibility.']].map(([title,copy])=><article key={title} className="rounded-3xl border border-rb-100 bg-white p-6 shadow-soft"><CheckCircle2 className="text-rb-600"/><h3 className="mt-5 text-xl font-black text-rb-900">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></div></section>
  <section className="bg-rb-50 py-24 sm:py-32"><div className={shell}><span className={eyebrow}>Our causes</span><h2 className={sectionTitle}>{causesTitle}</h2><p className={sectionCopy}>{causesCopy}</p><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{causes.map(([title,copy],i)=><article key={title} className="rounded-[2rem] border border-rb-100 bg-white p-7"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-rb-800 font-black text-white">0{i+1}</div><h3 className="mt-6 text-2xl font-black text-rb-900">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></div></section>
  <section className="py-24 sm:py-32"><div className={shell}><div className="rounded-[2.5rem] bg-rb-900 p-7 text-white shadow-xl sm:p-10 lg:p-14"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><span className="inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-gold">Transparency first</span><h2 className="mt-5 text-4xl font-black tracking-[-.04em] sm:text-5xl">{impactTitle}</h2><p className="mt-5 leading-8 text-white/70">{impactCopy}</p><Link to="/impact" className="mt-6 inline-flex items-center gap-2 font-black text-gold">Explore impact <ArrowRight size={17}/></Link></div><div className="grid gap-4 sm:grid-cols-2">{[['Funds received','Donation and group contribution records'],['Funds allocated','Cause and campaign allocation'],['Work completed','Field updates and project status'],['Impact documented','Stories, media and reports']].map(([title,copy])=><div key={title} className="rounded-3xl border border-white/10 bg-white/10 p-6"><ShieldCheck className="text-gold"/><h3 className="mt-4 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-white/65">{copy}</p></div>)}</div></div></div></div></section>
  <section className="py-24 sm:py-32"><div className={shell}><span className={eyebrow}>Stories of change</span><h2 className={sectionTitle}>{storiesTitle}</h2><Link to="/stories" className="mt-6 inline-flex items-center gap-2 font-black text-rb-700">View stories <ArrowRight size={17}/></Link></div></section>
  <section className="bg-[#fff1dd] py-24 sm:py-28"><div className={`${shell} grid gap-6 lg:grid-cols-3`}>{[[HandHeart,'Volunteer','Give your time and skills to field initiatives and community drives.','/volunteer'],[Users,'Partner','Collaborate as a company, institution, NGO or community partner.','/partner'],[Heart,'Donate','Support the general foundation fund or choose a specific verified campaign.','/donate']].map(([Icon,title,copy,path])=><Link to={path} key={title} className="rounded-3xl p-6 hover:bg-white/60"><Icon size={34} className="text-rb-700"/><h3 className="mt-5 text-3xl font-black text-rb-900">{title}</h3><p className="mt-3 leading-7 text-slate-700">{copy}</p></Link>)}</div></section>
  <SiteFooter/><FloatingActions/>
 </main>
}
export default App
